###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file el.xml.
# The source file version number was 1.69, generated on
# 2006/10/26 22:46:08.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::el;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::el::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Δευτέρα",
"Τρίτη",
"Τετάρτη",
"Πέμπτη",
"Παρασκευή",
"Σάββατο",
"Κυριακή",
);

my @day_abbreviations = (
"Δευ",
"Τρι",
"Τετ",
"Πεμ",
"Παρ",
"Σαβ",
"Κυρ",
);

my @day_narrows = (
"Δ",
"Τ",
"Τ",
"Π",
"Π",
"Σ",
"Κ",
);

my @month_names = (
"Ιανουαρίου",
"Φεβρουαρίου",
"Μαρτίου",
"Απριλίου",
"Μαΐου",
"Ιουνίου",
"Ιουλίου",
"Αυγούστου",
"Σεπτεμβρίου",
"Οκτωβρίου",
"Νοεμβρίου",
"Δεκεμβρίου",
);

my @month_abbreviations = (
"Ιαν",
"Φεβ",
"Μαρ",
"Απρ",
"Μαϊ",
"Ιουν",
"Ιουλ",
"Αυγ",
"Σεπ",
"Οκτ",
"Νοε",
"Δεκ",
);

my @month_narrows = (
"Ι",
"Φ",
"Μ",
"Α",
"Μ",
"Ι",
"Ι",
"Α",
"Σ",
"Ο",
"Ν",
"Δ",
);

my @quarter_names = (
"1ο\ τρίμηνο",
"2ο\ τρίμηνο",
"3ο\ τρίμηνο",
"4ο\ τρίμηνο",
);

my @am_pms = (
"ΠΜ",
"ΜΜ",
);

my @era_abbreviations = (
"π\.Χ\.",
"μ\.Χ\.",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%d\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%d\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%d\ \%b\ \%\{ce_year\}" }
sub short_date_format              { "\%d\/\%m\/\%\{ce_year\}" }
sub full_time_format               { "\%\{hour_12\}\:\%M\:\%S\ \%p\ \%\{time_zone_long_name\}" }
sub long_time_format               { "\%\{hour_12\}\:\%M\:\%S\ \%p\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%\{hour_12\}\:\%M\:\%S\ \%p" }
sub short_time_format              { "\%\{hour_12\}\:\%M\ \%p" }
sub date_parts_order               { $date_parts_order }



1;

