###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file en_ZA.xml.
# The source file version number was 1.39, generated on
# 2006/06/28 01:23:32.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::en_ZA;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::en;

@DateTime::Locale::en_ZA::ISA = qw(DateTime::Locale::en);

my $date_parts_order = "ymd";


sub full_date_format               { "\%A\ \%d\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%d\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%d\ \%b\ \%\{ce_year\}" }
sub short_date_format              { "\%\{ce_year\}\/\%m\/\%d" }
sub full_time_format               { "\%\{hour_12\}\:\%M\:\%S\ \%p" }
sub long_time_format               { "\%\{hour_12\}\:\%M\:\%S\ \%p" }
sub date_parts_order               { $date_parts_order }



1;

