###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file fr.xml.
# The source file version number was 1.85, generated on
# 2006/10/26 22:56:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::fr;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::fr::ISA = qw(DateTime::Locale::root);

my @day_names = (
"lundi",
"mardi",
"mercredi",
"jeudi",
"vendredi",
"samedi",
"dimanche",
);

my @day_abbreviations = (
"lun\.",
"mar\.",
"mer\.",
"jeu\.",
"ven\.",
"sam\.",
"dim\.",
);

my @day_narrows = (
"L",
"M",
"M",
"J",
"V",
"S",
"D",
);

my @month_names = (
"janvier",
"février",
"mars",
"avril",
"mai",
"juin",
"juillet",
"août",
"septembre",
"octobre",
"novembre",
"décembre",
);

my @month_abbreviations = (
"janv\.",
"févr\.",
"mars",
"avr\.",
"mai",
"juin",
"juil\.",
"août",
"sept\.",
"oct\.",
"nov\.",
"déc\.",
);

my @month_narrows = (
"J",
"F",
"M",
"A",
"M",
"J",
"J",
"A",
"S",
"O",
"N",
"D",
);

my @quarter_names = (
"1er\ trimestre",
"2e\ trimestre",
"3e\ trimestre",
"4e\ trimestre",
);

my @quarter_abbreviations = (
"T1",
"T2",
"T3",
"T4",
);

my @era_names = (
"av\.\ J\.\-C\.",
"ap\.\ J\.\-C\.",
);

my @era_abbreviations = (
"av\.\ J\.\-C\.",
"apr\.\ J\.\-C\.",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\ \%\{day\}\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\ \%b\ \%y" }
sub short_date_format              { "\%d\/\%m\/\%y" }
sub full_time_format               { "\%H\ h\ \%M\ \%\{time_zone_long_name\}" }
sub date_parts_order               { $date_parts_order }



1;

