###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ga.xml.
# The source file version number was 1.51, generated on
# 2006/06/27 23:30:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ga;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ga::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Dé\ Luain",
"Dé\ Máirt",
"Dé\ Céadaoin",
"Déardaoin",
"Dé\ hAoine",
"Dé\ Sathairn",
"Dé\ Domhnaigh",
);

my @day_abbreviations = (
"Luan",
"Máirt",
"Céad",
"Déar",
"Aoine",
"Sath",
"Domh",
);

my @month_names = (
"Eanáir",
"Feabhra",
"Márta",
"Aibreán",
"Bealtaine",
"Meitheamh",
"Iúil",
"Lúnasa",
"Meán\ Fómhair",
"Deireadh\ Fómhair",
"Samhain",
"Nollaig",
);

my @month_abbreviations = (
"Ean",
"Feabh",
"Márta",
"Aib",
"Beal",
"Meith",
"Iúil",
"Lún",
"MFómh",
"DFómh",
"Samh",
"Noll",
);

my @month_narrows = (
"E",
"F",
"M",
"A",
"B",
"M",
"I",
"L",
"M",
"D",
"S",
"N",
);

my @quarter_names = (
"1ú\ ráithe",
"2ú\ ráithe",
"3ú\ ráithe",
"4ú\ ráithe",
);

my @quarter_abbreviations = (
"R1",
"R2",
"R3",
"R4",
);

my @am_pms = (
"a\.m\.",
"p\.m\.",
);

my @era_abbreviations = (
"RC",
"AD",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }



1;

