###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file gaa.xml.
# The source file version number was 1.13, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::gaa;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::gaa::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Dzu",
"Dzufo",
"Sho",
"Soo",
"Sohaa",
"Ho",
"Hogbaa",
);

my @day_abbreviations = (
"Dzu",
"Dzf",
"Sho",
"Soo",
"Soh",
"Ho",
"Hog",
);

my @month_names = (
"Aharabata",
"Oflo",
"Ochokrikri",
"Abeibee",
"Agbeinaa",
"Otukwadan",
"Maawe",
"Manyawale",
"Gbo",
"Anton",
"Alemle",
"Afuabee",
);

my @month_abbreviations = (
"Aha",
"Ofl",
"Och",
"Abe",
"Agb",
"Otu",
"Maa",
"Man",
"Gbo",
"Ant",
"Ale",
"Afu",
);

my @am_pms = (
"LB",
"SN",
);

my @era_names = (
"Dani\ Jesu",
"KJ",
);

my @era_abbreviations = (
"DJ",
"KJ",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

