###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file gl.xml.
# The source file version number was 1.39, generated on
# 2006/06/27 23:30:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::gl;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::gl::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Luns",
"Martes",
"Mércores",
"Xoves",
"Venres",
"Sábado",
"Domingo",
);

my @day_abbreviations = (
"Lun",
"Mar",
"Mér",
"Xov",
"Ven",
"Sáb",
"Dom",
);

my @month_names = (
"Xaneiro",
"Febreiro",
"Marzo",
"Abril",
"Maio",
"Xuño",
"Xullo",
"Agosto",
"Setembro",
"Outubro",
"Novembro",
"Decembro",
);

my @month_abbreviations = (
"Xan",
"Feb",
"Mar",
"Abr",
"Mai",
"Xuñ",
"Xul",
"Ago",
"Set",
"Out",
"Nov",
"Dec",
);

my @quarter_names = (
"1er\ trimestre",
"2on\ trimestre",
"3er\ trimestre",
"4rt\ trimestre",
);

my @quarter_abbreviations = (
"T1",
"T2",
"T3",
"T4",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }



1;

