###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file kcg.xml.
# The source file version number was 1.11, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::kcg;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::kcg::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Tanii",
"Talata",
"Larba",
"Lamit",
"Juma",
"Asabat",
"Ladi",
);

my @day_abbreviations = (
"Tan",
"Tal",
"Lar",
"Lam",
"Jum",
"Asa",
"Lad",
);

my @month_names = (
"Zwat\ Juwung",
"Zwat\ Swiyang",
"Zwat\ Tsat",
"Zwat\ Nyai",
"Zwat\ Tswon",
"Zwat\ Ataah",
"Zwat\ Anatat",
"Zwat\ Arinai",
"Zwat\ Akubunyung",
"Zwat\ Swag",
"Zwat\ Mangjuwang",
"Zwat\ Swag\-Ma\-Suyang",
);

my @month_abbreviations = (
"Juw",
"Swi",
"Tsa",
"Nya",
"Tsw",
"Ata",
"Ana",
"Ari",
"Aku",
"Swa",
"Man",
"Mas",
);

my @era_names = (
"Gabanin\ Miladi",
"Miladi",
);

my @era_abbreviations = (
"GM",
"M",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

