###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file kk.xml.
# The source file version number was 1.39, generated on
# 2006/06/27 23:30:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::kk;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::kk::ISA = qw(DateTime::Locale::root);

my @day_names = (
"дуйсенбі",
"сейсенбі",
"сәренбі",
"бейсенбі",
"жұма",
"сенбі",
"жексені",
);

my @day_abbreviations = (
"дс\.",
"сс\.",
"ср\.",
"бс\.",
"жм\.",
"сһ\.",
"жс\.",
);

my @month_names = (
"қаңтар",
"ақпан",
"наурыз",
"сәуір",
"мамыр",
"маусым",
"шілде",
"тамыз",
"қыркүйек",
"қазан",
"қараша",
"желтоқсан",
);

my @month_abbreviations = (
"қаң\.",
"ақп\.",
"нау\.",
"сәу\.",
"мам\.",
"мау\.",
"шіл\.",
"там\.",
"қыр\.",
"қаз\.",
"қар\.",
"желт\.",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub full_date_format               { "\%A\,\ \%\{day\}\ \%B\ \%\{ce_year\}\ ж\." }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}\ ж\." }
sub medium_date_format             { "\%d\.\%m\.\%\{ce_year\}" }
sub short_date_format              { "\%d\.\%m\.\%y" }
sub date_parts_order               { $date_parts_order }



1;

