###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file kn.xml.
# The source file version number was 1.46, generated on
# 2006/06/25 00:18:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::kn;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::kn::ISA = qw(DateTime::Locale::root);

my @day_names = (
"ಸೋಮವಾರ",
"ಮಂಗಳವಾರ",
"ಬುಧವಾರ",
"ಗುರುವಾರ",
"ಶುಕ್ರವಾರ",
"ಶನಿವಾರ",
"ರವಿವಾರ",
);

my @day_abbreviations = (
"ಸೋ\.",
"ಮಂ\.",
"ಬು\.",
"ಗು\.",
"ಶು\.",
"ಶನಿ\.",
"ರ\.",
);

my @month_names = (
"ಜನವರೀ",
"ಫೆಬ್ರವರೀ",
"ಮಾರ್ಚ್",
"ಎಪ್ರಿಲ್",
"ಮೆ",
"ಜೂನ್",
"ಜುಲೈ",
"ಆಗಸ್ಟ್",
"ಸಪ್ಟೆಂಬರ್",
"ಅಕ್ಟೋಬರ್",
"ನವೆಂಬರ್",
"ಡಿಸೆಂಬರ್",
);

my @month_abbreviations = (
"ಜನವರೀ",
"ಫೆಬ್ರವರೀ",
"ಮಾರ್ಚ್",
"ಎಪ್ರಿಲ್",
"ಮೆ",
"ಜೂನ್",
"ಜುಲೈ",
"ಆಗಸ್ಟ್",
"ಸಪ್ಟೆಂಬರ್",
"ಅಕ್ಟೋಬರ್",
"ನವೆಂಬರ್",
"ಡಿಸೆಂಬರ್",
);

my @quarter_names = (
"ಒಂದು\ \ 1",
"ಎರಡು\ 2",
"ಮೂರು\ 3",
"ನಾಲೃಕ\ \ 4",
);

my @am_pms = (
"ಪೂರ್ವಾಹ್ನ",
"ಅಪರಾಹ್ನ",
);

my @era_names = (
"ಈಸಪೂವ೯\.",
"ಸನ್\.",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }



1;

