###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ln.xml.
# The source file version number was 1.18, generated on
# 2006/07/11 19:26:44.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ln;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ln::ISA = qw(DateTime::Locale::root);

my @day_names = (
"mokɔlɔ\ ya\ libosó",
"mokɔlɔ\ ya\ míbalé",
"mokɔlɔ\ ya\ mísáto",
"mokɔlɔ\ ya\ mínéi",
"mokɔlɔ\ ya\ mítáno",
"mpɔ́sɔ",
"eyenga",
);

my @day_abbreviations = (
"m1",
"m2",
"m3",
"m4",
"m5",
"mps",
"eye",
);

my @month_names = (
"sánzá\ ya\ yambo",
"sánzá\ ya\ míbalé",
"sánzá\ ya\ mísáto",
"sánzá\ ya\ mínéi",
"sánzá\ ya\ mítáno",
"sánzá\ ya\ motóbá",
"sánzá\ ya\ nsambo",
"sánzá\ ya\ mwambe",
"sánzá\ ya\ libwa",
"sánzá\ ya\ zómí",
"sánzá\ ya\ zómí\ na\ mɔ̌kɔ́",
"sánzá\ ya\ zómí\ na\ míbalé",
);

my @month_abbreviations = (
"s1",
"s2",
"s3",
"s4",
"s5",
"s6",
"s7",
"s8",
"s9",
"s10",
"s11",
"s12",
);

my @quarter_names = (
"sánzá\ mísáto\ ya\ yambo",
"sánzá\ mísáto\ ya\ míbalé",
"sánzá\ mísáto\ ya\ mísáto",
"sánzá\ mísáto\ ya\ mínéi",
);

my @quarter_abbreviations = (
"SM1",
"SM2",
"SM3",
"SM4",
);

my @era_names = (
"libosó\ ya\ Y\.\-K\.",
"nsima\ ya\ Y\.\-K\.",
);

my @era_abbreviations = (
"libosó\ ya\ Y\.\-K\.",
"nsima\ ya\ Y\.\-K\.",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

