###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file sv_SE.xml.
# The source file version number was 1.44, generated on
# 2006/07/11 19:27:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::sv_SE;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::sv;

@DateTime::Locale::sv_SE::ISA = qw(DateTime::Locale::sv);



sub long_date_format               { "\%a\ \%\{day\}\ \%b\ \%\{ce_year\}" }



1;

