'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace MySoapRef
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="mhsoapServiceSoap", [Namespace]:="urn:mhsoap")>  _
    Public Class mhsoap
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://misterhouse:8080/bin/soapcgi.pl"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:mhsoap/ListObjectTypes", RequestNamespace:="urn:mhsoap", ResponseNamespace:="urn:mhsoap")>  _
        Public Function ListObjectTypes() As <System.Xml.Serialization.SoapElementAttribute("return")> String()
            Dim results() As Object = Me.Invoke("ListObjectTypes", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginListObjectTypes(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ListObjectTypes", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndListObjectTypes(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:mhsoap/ListObjectsByType", RequestNamespace:="urn:mhsoap", ResponseNamespace:="urn:mhsoap")>  _
        Public Function ListObjectsByType(ByVal object_type As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String()
            Dim results() As Object = Me.Invoke("ListObjectsByType", New Object() {object_type})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginListObjectsByType(ByVal object_type As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ListObjectsByType", New Object() {object_type}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndListObjectsByType(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:mhsoap/SetItemState", RequestNamespace:="urn:mhsoap", ResponseNamespace:="urn:mhsoap")>  _
        Public Function SetItemState(ByVal ItemToSet As String, ByRef State As String) As <System.Xml.Serialization.SoapElementAttribute("return")> Integer
            Dim results() As Object = Me.Invoke("SetItemState", New Object() {ItemToSet, State})
            State = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginSetItemState(ByVal ItemToSet As String, ByVal State As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SetItemState", New Object() {ItemToSet, State}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSetItemState(ByVal asyncResult As System.IAsyncResult, ByRef State As String) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            State = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:mhsoap/GetItemState", RequestNamespace:="urn:mhsoap", ResponseNamespace:="urn:mhsoap")>  _
        Public Function GetItemState(ByVal ItemToGet As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("GetItemState", New Object() {ItemToGet})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetItemState(ByVal ItemToGet As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetItemState", New Object() {ItemToGet}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetItemState(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
