###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file af.xml.
# The source file version number was 1.48, generated on
# 2006/06/28 20:38:29.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::af;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::af::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Maandag",
"Dinsdag",
"Woensdag",
"Donderdag",
"Vrydag",
"Saterdag",
"Sondag",
);

my @day_abbreviations = (
"Ma\.",
"Di\.",
"Wo\.",
"Do\.",
"Vr\.",
"Sa\.",
"So\.",
);

my @month_names = (
"Januarie",
"Februarie",
"Maart",
"April",
"Mei",
"Junie",
"Julie",
"Augustus",
"September",
"Oktober",
"November",
"Desember",
);

my @month_abbreviations = (
"Jan\.",
"Feb\.",
"Mrt\.",
"Apr\.",
"Mei",
"Jun\.",
"Jul\.",
"Aug\.",
"Sep\.",
"Okt\.",
"Nov\.",
"Des\.",
);

my @quarter_names = (
"1ste\ kwartaal",
"2de\ kwartaal",
"3de\ kwartaal",
"4de\ kwartaal",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);

my @am_pms = (
"vm\.",
"nm\.",
);

my @era_names = (
"voor\ Christus",
"na\ Christus",
);

my @era_abbreviations = (
"v\.C\.",
"n\.C\.",
);

my $date_parts_order = "ymd";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\ \%\{day\}\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\ \%b\ \%\{ce_year\}" }
sub short_date_format              { "\%\{ce_year\}\-\%m\-\%d" }
sub date_parts_order               { $date_parts_order }



1;

