###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ar_JO.xml.
# The source file version number was 1.38, generated on
# 2006/06/27 23:30:53.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ar_JO;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::ar;

@DateTime::Locale::ar_JO::ISA = qw(DateTime::Locale::ar);

my @day_abbreviations = (
"الاثنين",
"الثلاثاء",
"الأربعاء",
"الخميس",
"الجمعة",
"السبت",
"الأحد",
);

my @month_names = (
"كانون\ الثاني",
"شباط",
"آذار",
"نيسان",
"أيار",
"حزيران",
"تموز",
"آب",
"أيلول",
"تشرين\ الأول",
"تشرين\ الثاني",
"كانون\ الأول",
);

my @month_abbreviations = (
"كانون\ الثاني",
"شباط",
"آذار",
"نيسان",
"أيار",
"حزيران",
"تموز",
"آب",
"أيلول",
"تشرين\ الأول",
"تشرين\ الثاني",
"كانون\ الأول",
);



sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }



1;

