###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file az.xml.
# The source file version number was 1.39, generated on
# 2006/06/27 23:30:53.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::az;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::az::ISA = qw(DateTime::Locale::root);

my @day_names = (
"bazar\ ertəsi",
"çərşənbə\ axşam",
"çərşənbə",
"cümə",
"cümə\ axşamı",
"şənbə",
"bazar",
);

my @day_abbreviations = (
"B\.e\.",
"Ç\.a\.",
"Ç\.",
"C\.a\.",
"C\.",
"Ş\.",
"B\.",
);

my @month_names = (
"Yanvar",
"Fevral",
"Mart",
"Aprel",
"May",
"İyun",
"İyul",
"Avqust",
"Sentyabr",
"Oktyabr",
"Noyabr",
"Dekabr",
);

my @month_abbreviations = (
"yan",
"fev",
"mar",
"apr",
"may",
"iyn",
"iyl",
"avq",
"sen",
"okt",
"noy",
"dek",
);

my @quarter_names = (
"1\-ci\ kvartal",
"2\-ci\ kvartal",
"3\-cü\ kvartal",
"4\-cü\ kvartal",
);

my @quarter_abbreviations = (
"1\-ci\ kv\.",
"2\-ci\ kv\.",
"3\-cü\ kv\.",
"4\-cü\ kv\.",
);

my @era_names = (
"eramızdan\ əvvəl",
"bizim\ eramızın",
);

my @era_abbreviations = (
"e\.ə\.",
"b\.e\.",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

