###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file az_Cyrl.xml.
# The source file version number was 1.18, generated on
# 2006/06/27 23:30:53.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::az_Cyrl;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::az;

@DateTime::Locale::az_Cyrl::ISA = qw(DateTime::Locale::az);

my @day_names = (
"базар\ ертәси",
"чәршәнбә\ ахшамы",
"чәршәнбә",
"ҹүмә\ ахшамы",
"ҹүмә",
"шәнбә",
"базар",
);

my @month_names = (
"јанвар",
"феврал",
"март",
"апрел",
"май",
"ијун",
"ијул",
"август",
"сентјабр",
"октјабр",
"нојабр",
"декабр",
);



sub day_names                      { \@day_names }
sub month_names                    { \@month_names }



1;

