###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file bg_BG.xml.
# The source file version number was 1.43, generated on
# 2006/08/04 21:59:10.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::bg_BG;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::bg;

@DateTime::Locale::bg_BG::ISA = qw(DateTime::Locale::bg);

my @era_names = (
"пр\.Хр\.",
"сл\.Хр\.",
);



sub era_names                      { \@era_names }



1;

