###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file bn.xml.
# The source file version number was 1.49, generated on
# 2006/06/27 23:30:53.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::bn;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::bn::ISA = qw(DateTime::Locale::root);

my @day_names = (
"সোমবার",
"মঙ্গলবার",
"বুধবার",
"বৃহষ্পতিবার",
"শুক্রবার",
"শনিবার",
"রবিবার",
);

my @day_abbreviations = (
"সোম",
"মঙ্গল",
"বুধ",
"বৃহস্পতি",
"শুক্র",
"শনি",
"রবি",
);

my @month_names = (
"জানুয়ারী",
"ফেব্রুয়ারী",
"মার্চ",
"এপ্রিল",
"মে",
"জুন",
"জুলাই",
"আগস্ট",
"সেপ্টেম্বর",
"অক্টোবর",
"নভেম্বর",
"ডিসেম্বর",
);

my @month_abbreviations = (
"জানুয়ারী",
"ফেব্রুয়ারী",
"মার্চ",
"এপ্রিল",
"মে",
"জুন",
"জুলাই",
"আগস্ট",
"সেপ্টেম্বর",
"অক্টোবর",
"নভেম্বর",
"ডিসেম্বর",
);

my @am_pms = (
"পূর্বাহ্ণ",
"অপরাহ্ণ",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub am_pms                         { \@am_pms }



1;

