###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file bs.xml.
# The source file version number was 1.22, generated on
# 2006/07/11 19:26:43.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::bs;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::bs::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Ponedjeljak",
"Utorak",
"Srijeda",
"Četvrtak",
"Petak",
"Subota",
"Nedjelja",
);

my @day_abbreviations = (
"Pon",
"Uto",
"Sri",
"Čet",
"Pet",
"Sub",
"Ned",
);

my @month_names = (
"Januar",
"Februar",
"Mart",
"April",
"Maj",
"Juni",
"Juli",
"Avgust",
"Septembar",
"Oktobar",
"Novembar",
"Decembar",
);

my @month_abbreviations = (
"Jan",
"Feb",
"Mar",
"Apr",
"Maj",
"Jun",
"Jul",
"Avg",
"Sep",
"Okt",
"Nov",
"Dec",
);

my @quarter_names = (
"Prvi\ kvartal",
"Drugi\ kvartal",
"Treći\ kvartal",
"Četvrti\ kvartal",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);

my @era_abbreviations = (
"BC",
"AD",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_abbreviations              { \@era_abbreviations }



1;

