###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file byn.xml.
# The source file version number was 1.40, generated on
# 2006/06/28 02:11:28.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::byn;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::byn::ISA = qw(DateTime::Locale::root);

my @day_names = (
"ሰኑ",
"ሰሊጝ",
"ለጓ\ ወሪ\ ለብዋ",
"ኣምድ",
"ኣርብ",
"ሰንበር\ ሽጓዅ",
"ሰንበር\ ቅዳዅ",
);

my @day_abbreviations = (
"ሰኑ",
"ሰሊጝ",
"ለጓ",
"ኣምድ",
"ኣርብ",
"ሰ\/ሽ",
"ሰ\/ቅ",
);

my @day_narrows = (
"ሰ",
"ሰ",
"ለ",
"ኣ",
"ኣ",
"ሰ",
"ሰ",
);

my @month_names = (
"ልደትሪ",
"ካብኽብቲ",
"ክብላ",
"ፋጅኺሪ",
"ክቢቅሪ",
"ምኪኤል\ ትጓ̅ኒሪ",
"ኰርኩ",
"ማርያም\ ትሪ",
"ያኸኒ\ መሳቅለሪ",
"መተሉ",
"ምኪኤል\ መሽወሪ",
"ተሕሳስሪ",
);

my @month_abbreviations = (
"ልደት",
"ካብኽ",
"ክብላ",
"ፋጅኺ",
"ክቢቅ",
"ም\/ት",
"ኰር",
"ማርያ",
"ያኸኒ",
"መተሉ",
"ም\/ም",
"ተሕሳ",
);

my @month_narrows = (
"ል",
"ካ",
"ክ",
"ፋ",
"ክ",
"ም",
"ኰ",
"ማ",
"ያ",
"መ",
"ም",
"ተ",
);

my @am_pms = (
"ፋዱስ\ ጃብ",
"ፋዱስ\ ደምቢ",
);

my @era_abbreviations = (
"ይጅ",
"ኣድ",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }



1;

