###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file cch.xml.
# The source file version number was 1.13, generated on
# 2006/06/28 01:23:32.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::cch;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::cch::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Wai\ Tunga",
"Toki\ Gitung",
"Tsam\ Kasuwa",
"Wai\ Na\ Nas",
"Wai\ Na\ Tiyon",
"Wai\ Na\ Chirim",
"Wai\ Yoka\ Bawai",
);

my @day_abbreviations = (
"Tung",
"T\.\ Tung",
"Tsan",
"Nas",
"Nat",
"Chir",
"Yok",
);

my @month_names = (
"Pen\ Dyon",
"Pen\ Ba\'a",
"Pen\ Atat",
"Pen\ Anas",
"Pen\ Atyon",
"Pen\ Achirim",
"Pen\ Atariba",
"Pen\ Awurr",
"Pen\ Shadon",
"Pen\ Shakur",
"Pen\ Kur\ Naba",
"Pen\ Kur\ Natat",
);

my @month_abbreviations = (
"Dyon",
"Baa",
"Atat",
"Anas",
"Atyo",
"Achi",
"Atar",
"Awur",
"Shad",
"Shak",
"Naba",
"Nata",
);

my @era_names = (
"Gabanin\ Miladi",
"Miladi",
);

my @era_abbreviations = (
"GM",
"M",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

