###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file de_AT.xml.
# The source file version number was 1.42, generated on
# 2006/06/28 01:23:32.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::de_AT;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::de;

@DateTime::Locale::de_AT::ISA = qw(DateTime::Locale::de);



sub full_date_format               { "\%A\,\ \%d\.\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%d\.\ \%B\ \%\{ce_year\}" }
sub full_time_format               { "\%H\:\%M\ Uhr\ \%\{time_zone_long_name\}" }



1;

