###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file eu_ES.xml.
# The source file version number was 1.39, generated on
# 2006/06/27 23:30:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::eu_ES;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::eu;

@DateTime::Locale::eu_ES::ISA = qw(DateTime::Locale::eu);

my $date_parts_order = "ymd";


sub full_date_format               { "\%A\,\ \%\{ce_year\}eko\ \%Bren\ \%da" }
sub long_date_format               { "\%a\,\ \%\{ce_year\}eko\ \%bren\ \%da" }
sub medium_date_format             { "\%y\-\%b\-\%d" }
sub short_date_format              { "\%y\-\%m\-\%d" }
sub date_parts_order               { $date_parts_order }



1;

