###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file fur.xml.
# The source file version number was 1.12, generated on
# 2006/07/11 19:26:44.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::fur;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::fur::ISA = qw(DateTime::Locale::root);

my @day_names = (
"lunis",
"martars",
"miercus",
"joibe",
"vinars",
"sabide",
"domenie",
);

my @day_abbreviations = (
"lun",
"mar",
"mie",
"joi",
"vin",
"sab",
"dom",
);

my @day_narrows = (
"L",
"M",
"M",
"J",
"V",
"S",
"D",
);

my @month_names = (
"Zenâr",
"Fevrâr",
"Març",
"Avrîl",
"Mai",
"Jugn",
"Lui",
"Avost",
"Setembar",
"Otubar",
"Novembar",
"Dicembar",
);

my @month_abbreviations = (
"Zen",
"Fev",
"Mar",
"Avr",
"Mai",
"Jug",
"Lui",
"Avo",
"Set",
"Otu",
"Nov",
"Dic",
);

my @month_narrows = (
"Z",
"F",
"M",
"A",
"M",
"J",
"L",
"A",
"S",
"O",
"N",
"D",
);

my @quarter_names = (
"Prin\ trimestri",
"Secont\ trimestri",
"Tierç\ trimestri",
"Cuart\ trimestri",
);

my @quarter_abbreviations = (
"T1",
"T2",
"T3",
"T4",
);

my @am_pms = (
"a\.",
"p\.",
);

my @era_names = (
"pdC",
"ddC",
);

my @era_abbreviations = (
"pdC",
"ddC",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}\ \%A" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\ \%b\ \%\{ce_year\}" }
sub short_date_format              { "\%\{day\}\/\%m\/\%y" }
sub date_parts_order               { $date_parts_order }



1;

