###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ha_Arab.xml.
# The source file version number was 1.13, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ha_Arab;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::ha;

@DateTime::Locale::ha_Arab::ISA = qw(DateTime::Locale::ha);

my @day_names = (
"لِتِنِنْ",
"تَلَتَ",
"لَرَبَ",
"أَلْحَمِسْ",
"جُمَعَ",
"أَسَبَرْ",
"لَحَدِ",
);

my @day_abbreviations = (
"لِت",
"تَل",
"لَر",
"أَلْح",
"جُم",
"أَسَ",
"لَح",
);

my @month_names = (
"جَنَيْرُ",
"ڢَبْرَيْرُ",
"مَرِسْ",
"أَڢْرِلُ",
"مَيُ",
"يُونِ",
"يُولِ",
"أَغُسْتَ",
"سَتُمْبَ",
"أُكْتوُبَ",
"نُوَمْبَ",
"دِسَمْبَ",
);

my @month_abbreviations = (
"جَن",
"ڢَب",
"مَر",
"أَڢْر",
"مَي",
"يُون",
"يُول",
"أَغُ",
"سَت",
"أُكْت",
"نُو",
"دِس",
);

my @am_pms = (
"A\.M\.",
"P\.M\.",
);

my @era_names = (
"غَبَنِنْ\ مِلَدِ",
"مِلَدِ",
);

my @era_abbreviations = (
"غَبَنِنْ\ مِلَدِ",
"مِلَدِ",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

