###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ia.xml.
# The source file version number was 1.10, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ia;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ia::ISA = qw(DateTime::Locale::root);

my @day_names = (
"lunedi",
"martedi",
"mercuridi",
"jovedi",
"venerdi",
"sabbato",
"dominica",
);

my @day_abbreviations = (
"lun",
"mar",
"mer",
"jov",
"ven",
"sab",
"dom",
);

my @month_names = (
"januario",
"februario",
"martio",
"april",
"maio",
"junio",
"julio",
"augusto",
"septembre",
"octobre",
"novembre",
"decembre",
);

my @month_abbreviations = (
"jan",
"feb",
"mar",
"apr",
"mai",
"jun",
"jul",
"aug",
"sep",
"oct",
"nov",
"dec",
);

my @quarter_names = (
"1\-me\ trimestre",
"2\-nde\ trimestre",
"3\-tie\ trimestre",
"4\-te\ trimestre",
);

my @quarter_abbreviations = (
"T1",
"T2",
"T3",
"T4",
);

my @am_pms = (
"a\.m\.",
"p\.m\.",
);

my @era_names = (
"ante\ Christo",
"post\ Christo",
);

my @era_abbreviations = (
"a\.Chr\.",
"p\.Chr\.",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

