###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file id.xml.
# The source file version number was 1.52, generated on
# 2006/07/07 21:00:32.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::id;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::id::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Senin",
"Selasa",
"Rabu",
"Kamis",
"Jumat",
"Sabtu",
"Minggu",
);

my @day_abbreviations = (
"Sen",
"Sel",
"Rab",
"Kam",
"Jum",
"Sab",
"Min",
);

my @month_names = (
"Januari",
"Februari",
"Maret",
"April",
"Mei",
"Juni",
"Juli",
"Agustus",
"September",
"Oktober",
"November",
"Desember",
);

my @month_abbreviations = (
"Jan",
"Feb",
"Mar",
"Apr",
"Mei",
"Jun",
"Jul",
"Agu",
"Sep",
"Okt",
"Nov",
"Des",
);

my @quarter_names = (
"kuartal\ pertama",
"kuartal\ kedua",
"kuartal\ ketiga",
"kuartal\ keempat",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }



1;

