###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ig.xml.
# The source file version number was 1.12, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ig;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ig::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Mọnde",
"Tiuzdee",
"Wenezdee",
"Tọọzdee",
"Fraịdee",
"Satọdee",
"Mbọsị\ Ụka",
);

my @day_abbreviations = (
"Mọn",
"Tiu",
"Wen",
"Tọọ",
"Fraị",
"Sat",
"Ụka",
);

my @month_names = (
"Jenụwarị",
"Febrụwarị",
"Maachị",
"Eprel",
"Mee",
"Juun",
"Julaị",
"Ọgọọst",
"Septemba",
"Ọktoba",
"Novemba",
"Disemba",
);

my @month_abbreviations = (
"Jen",
"Feb",
"Maa",
"Epr",
"Mee",
"Juu",
"Jul",
"Ọgọ",
"Sep",
"Ọkt",
"Nov",
"Dis",
);

my @am_pms = (
"A\.M\.",
"P\.M\.",
);

my @era_names = (
"Tupu\ Kristi",
"Afọ\ Kristi",
);

my @era_abbreviations = (
"T\.K\.",
"A\.K\.",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

