###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file it_CH.xml.
# The source file version number was 1.39, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::it_CH;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::it;

@DateTime::Locale::it_CH::ISA = qw(DateTime::Locale::it);

my $date_parts_order = "dmy";


sub full_date_format               { "\%A\,\ \%\{day\}\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\-\%b\-\%y" }
sub short_date_format              { "\%d\.\%m\.\%y" }
sub full_time_format               { "\%H\.\%M\:\%S\ h\ \%\{time_zone_long_name\}" }
sub date_parts_order               { $date_parts_order }



1;

