###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file iu.xml.
# The source file version number was 1.25, generated on
# 2006/06/24 23:27:01.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::iu;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::iu::ISA = qw(DateTime::Locale::root);

my @day_names = (
"ᓇᒡᒐᔾᔭᐅ",
"ᓇᒡᒐᔾᔭᐅᓕᖅᑭ",
"ᐱᖓᑦᓯᖅ",
"ᓯᑕᒻᒥᖅ",
"ᑕᓪᓕᕐᒥᖅ",
"ᓈᑦᓰᖑᔭᓕᖅᕿ",
"ᓈᑦᓰᖑᔭ",
);

my @day_abbreviations = (
"ᓇᒡᒐᔾᔭᐅ",
"ᓇᒡᒐᔾᔭᐅᓕᖅᑭ",
"ᐱᖓᑦᓯᖅ",
"ᓯᑕᒻᒥᖅ",
"ᑕᓪᓕᕐᒥᖅ",
"ᓈᑦᓰᖑᔭᓕᖅᕿ",
"ᓈᑦᓰᖑᔭ",
);

my @month_names = (
"ᔭᓐᓄᐊᓕ",
"ᕕᕝᕗᐊᓕ",
"ᒫᑦᓯ",
"ᐊᐃᑉᐳᓗ",
"ᒪᐃ",
"ᔫᓂ",
"ᔪᓚᐃ",
"ᐊᐅᒡᒍᓯ",
"ᓰᑦᑏᕝᕙ",
"ᐆᑦᑑᕝᕙ",
"ᓅᕙᐃᕝᕙ",
"ᑏᓰᕝᕙ",
);

my @month_abbreviations = (
"ᔭᓐᓄᐊᓕ",
"ᕕᕝᕗᐊᓕ",
"ᒫᑦᓯ",
"ᐊᐃᑉᐳᓗ",
"ᒪᐃ",
"ᔫᓂ",
"ᔪᓚᐃ",
"ᐊᐅᒡᒍᓯ",
"ᓰᑦᑏᕝᕙ",
"ᐆᑦᑑᕝᕙ",
"ᓅᕙᐃᕝᕙ",
"ᑏᓰᕝᕙ",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }



1;

