###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file km.xml.
# The source file version number was 1.45, generated on
# 2006/06/28 04:18:18.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::km;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::km::ISA = qw(DateTime::Locale::root);

my @day_names = (
"​ថ្ងៃច័ន្ទ",
"ថ្ងៃអង្គារ",
"ថ្ងៃពុធ",
"ថ្ងៃព្រហស្បតិ៍",
"ថ្ងៃសុក្រ",
"ថ្ងៃសៅរ៍",
"ថ្ងៃអាទិត្យ",
);

my @day_abbreviations = (
"ច",
"អ",
"ពុ",
"ព្រ",
"សុ",
"ស",
"អា",
);

my @month_names = (
"មករា",
"កុម្ភៈ",
"មិនា",
"មេសា",
"ឧសភា",
"មិថុនា",
"កក្កដា",
"សីហា",
"កញ្ញា",
"តុលា",
"វិច្ឆិកា",
"ធ្នូ",
);

my @month_abbreviations = (
"១",
"២",
"៣",
"៤",
"៥",
"៦",
"៧",
"៨",
"៩",
"១០",
"១១",
"១២",
);

my @quarter_names = (
"ត្រីមាសទី១",
"ត្រីមាសទី២",
"ត្រីមាសទី៣",
"ត្រីមាសទី៤",
);

my @quarter_abbreviations = (
"ត្រី១",
"ត្រី២",
"ត្រី៣",
"ត្រី៤",
);

my @am_pms = (
"ព្រឹក",
"ល្ងាច",
);

my @era_names = (
"មុន​គ្រិស្តសករាជ",
"គ្រិស្តសករាជ",
);

my @era_abbreviations = (
"មុន​គ\.ស\.",
"គ\.ស\.",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\ ថ្ងៃ\ \%\{day\}\ ខែ\ \%B\ ឆ្នាំ\ \ \%\{ce_year\}" }
sub long_date_format               { "\%A\ ថ្ងៃ\ \%\{day\}\ ខែ\ \%B\ ឆ្នាំ\ \ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub short_date_format              { "\%\{day\}\/\%\{month\}\/\%\{ce_year\}" }
sub full_time_format               { "\%\{hour\}\ ម៉ោង\ \%\{minute\}\ នាទី\ \%S\ វិនាទី​\ \%\{time_zone_long_name\}" }
sub long_time_format               { "\%\{hour\}\ ម៉ោង\ \%\{minute\}\ នាទី\ \%S\ វិនាទី​" }
sub medium_time_format             { "\%\{hour\}\:\%M\:\%S" }
sub short_time_format              { "\%\{hour\}\:\%M" }
sub date_parts_order               { $date_parts_order }



1;

