###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file lv.xml.
# The source file version number was 1.57, generated on
# 2006/06/27 23:30:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::lv;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::lv::ISA = qw(DateTime::Locale::root);

my @day_names = (
"pirmdiena",
"otrdiena",
"trešdiena",
"ceturtdiena",
"piektdiena",
"sestdiena",
"svētdiena",
);

my @day_abbreviations = (
"P",
"O",
"T",
"C",
"Pk",
"S",
"Sv",
);

my @month_names = (
"janvāris",
"februāris",
"marts",
"aprīlis",
"maijs",
"jūnijs",
"jūlijs",
"augusts",
"septembris",
"oktobris",
"novembris",
"decembris",
);

my @month_abbreviations = (
"Jan",
"Feb",
"Mar",
"Apr",
"Mai",
"Jūn",
"Jūl",
"Aug",
"Sep",
"Okt",
"Nov",
"Dec",
);

my @quarter_names = (
"1\.\ ceturksnis",
"2\.\ ceturksnis",
"3\.\ ceturksnis",
"4\.\ ceturksnis",
);

my @quarter_abbreviations = (
"C1",
"C2",
"C3",
"C4",
);

my @era_names = (
"pirms\ mūsu\ ēras",
"mūsu\ ērā",
);

my @era_abbreviations = (
"pmē",
"mē",
);

my $date_parts_order = "ydm";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%\{ce_year\}\.\ gada\ \%\{day\}\.\ \%B" }
sub long_date_format               { "\%\{ce_year\}\.\ gada\ \%\{day\}\.\ \%B" }
sub medium_date_format             { "\%\{ce_year\}\.\%\{day\}\.\%\{month\}" }
sub short_date_format              { "\%y\.\%\{day\}\.\%\{month\}" }
sub date_parts_order               { $date_parts_order }



1;

