###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file mk.xml.
# The source file version number was 1.58, generated on
# 2006/06/27 23:30:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::mk;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::mk::ISA = qw(DateTime::Locale::root);

my @day_names = (
"понеделник",
"вторник",
"среда",
"четврток",
"петок",
"сабота",
"недела",
);

my @day_abbreviations = (
"пон\.",
"вт\.",
"сре\.",
"чет\.",
"пет\.",
"саб\.",
"нед\.",
);

my @day_narrows = (
"п",
"в",
"с",
"ч",
"п",
"с",
"н",
);

my @month_names = (
"јануари",
"февруари",
"март",
"април",
"мај",
"јуни",
"јули",
"август",
"септември",
"октомври",
"ноември",
"декември",
);

my @month_abbreviations = (
"јан\.",
"фев\.",
"мар\.",
"апр\.",
"мај\.",
"јун\.",
"јул\.",
"авг\.",
"септ\.",
"окт\.",
"ноем\.",
"декем\.",
);

my @month_narrows = (
"ј",
"ф",
"м",
"а",
"м",
"ј",
"ј",
"а",
"се",
"о",
"но",
"д",
);

my @era_abbreviations = (
"пр\.н\.е\.",
"ае\.",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%d\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%d\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%d\.\%\{month\}\.\%\{ce_year\}" }
sub short_date_format              { "\%d\.\%\{month\}\.\%y" }
sub date_parts_order               { $date_parts_order }



1;

