###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file mr.xml.
# The source file version number was 1.50, generated on
# 2006/06/28 06:03:59.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::mr;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::mr::ISA = qw(DateTime::Locale::root);

my @day_names = (
"सोमवार",
"मंगळवार",
"बुधवार",
"गुरुवार",
"शुक्रवार",
"शनिवार",
"रविवार",
);

my @day_abbreviations = (
"सोम",
"मंगळ",
"बुध",
"गुरु",
"शुक्र",
"शनि",
"रवि",
);

my @month_names = (
"जानेवारी",
"फेबृवारी",
"मार्च",
"एप्रिल",
"मे",
"जून",
"जुलै",
"ओगस्ट",
"सेप्टेंबर",
"ओक्टोबर",
"नोव्हेंबर",
"डिसेंबर",
);

my @month_abbreviations = (
"जानेवारी",
"फेबृवारी",
"मार्च",
"एप्रिल",
"मे",
"जून",
"जुलै",
"ओगस्ट",
"सेप्टेंबर",
"ओक्टोबर",
"नोव्हेंबर",
"डिसेंबर",
);

my @am_pms = (
"म\.पू\.",
"म\.नं\.",
);

my @era_abbreviations = (
"ईसापूर्व",
"सन",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }



1;

