###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ny.xml.
# The source file version number was 1.13, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ny;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ny::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Lolemba",
"Lachiwiri",
"Lachitatu",
"Lachinayi",
"Lachisanu",
"Loweruka",
"Lamulungu",
);

my @day_abbreviations = (
"Lem",
"Wir",
"Tat",
"Nai",
"San",
"Wer",
"Mul",
);

my @month_names = (
"Januwale",
"Febuluwale",
"Malichi",
"Epulo",
"Mei",
"Juni",
"Julai",
"Ogasiti",
"Seputemba",
"Okutoba",
"Novemba",
"Disemba",
);

my @month_abbreviations = (
"Jan",
"Feb",
"Mal",
"Epu",
"Mei",
"Jun",
"Jul",
"Oga",
"Sep",
"Oku",
"Nov",
"Dis",
);

my @era_names = (
"BC",
"AD",
);

my @era_abbreviations = (
"BC",
"AD",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

