###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file pa.xml.
# The source file version number was 1.45, generated on
# 2006/06/27 23:30:54.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::pa;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::pa::ISA = qw(DateTime::Locale::root);

my @day_names = (
"ਸੋਮਵਾਰ",
"ਮੰਗਲਵਾਰ",
"ਬੁੱਧਵਾਰ",
"ਵੀਰਵਾਰ",
"ਸ਼ੁੱਕਰਵਾਰ",
"ਸ਼ਨਿੱਚਰਵਾਰ",
"ਐਤਵਾਰ",
);

my @day_abbreviations = (
"ਸੋਮ\.",
"ਮੰਗਲ\.",
"ਬੁੱਧ\.",
"ਵੀਰ\.",
"ਸ਼ੁੱਕਰ\.",
"ਸ਼ਨਿੱਚਰ\.",
"ਐਤ\.",
);

my @month_names = (
"ਜਨਵਰੀ",
"ਫ਼ਰਵਰੀ",
"ਮਾਰਚ",
"ਅਪ੍ਰੈਲ",
"ਮਈ",
"ਜੂਨ",
"ਜੁਲਾਈ",
"ਅਗਸਤ",
"ਸਤੰਬਰ",
"ਅਕਤੂਬਰ",
"ਨਵੰਬਰ",
"ਦਸੰਬਰ",
);

my @month_abbreviations = (
"ਜਨਵਰੀ",
"ਫ਼ਰਵਰੀ",
"ਮਾਰਚ",
"ਅਪ੍ਰੈਲ",
"ਮਈ",
"ਜੂਨ",
"ਜੁਲਾਈ",
"ਅਗਸਤ",
"ਸਤੰਬਰ",
"ਅਕਤੂਬਰ",
"ਨਵੰਬਰ",
"ਦਸੰਬਰ",
);

my @quarter_names = (
"ਪਹਿਲਾਂ\ ਚੌਥਾਈ",
"ਦੂਜਾ\ ਚੌਥਾਈ",
"ਤੀਜਾ\ ਚੌਥਾਈ",
"ਚੌਥਾ\ ਚੌਥਾਈ",
);

my @am_pms = (
"ਸਵੇਰੇ",
"ਸ਼ਾਮ",
);

my @era_names = (
"ਈਸਾਪੂਰਵ",
"ਸੰਨ",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }



1;

