###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file pa_Arab.xml.
# The source file version number was 1.11, generated on
# 2006/07/17 01:03:00.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::pa_Arab;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::pa;

@DateTime::Locale::pa_Arab::ISA = qw(DateTime::Locale::pa);

my @day_names = (
"پیر",
"منگل",
"بُدھ",
"جمعرات",
"جمعہ",
"ہفتہ",
"اتوار",
);

my @month_names = (
"جنوری",
"فروری",
"مارچ",
"اپریل",
"مئ",
"جون",
"جولائی",
"اگست",
"ستمبر",
"اکتوبر",
"نومبر",
"دسمبر",
);

my @quarter_names = (
"چوتھاي\ پہلاں",
"چوتھاي\ دوجا",
"چوتھاي\ تيجا",
"چوتھاي\ چوتھا",
);

my @era_names = (
"ايساپورو",
"سں",
);



sub day_names                      { \@day_names }
sub month_names                    { \@month_names }
sub quarter_names                  { \@quarter_names }
sub era_names                      { \@era_names }



1;

