###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file pt_PT.xml.
# The source file version number was 1.53, generated on
# 2006/07/11 19:27:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::pt_PT;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::pt;

@DateTime::Locale::pt_PT::ISA = qw(DateTime::Locale::pt);

my $date_parts_order = "ymd";


sub medium_date_format             { "\%\{ce_year\}\/\%m\/\%d" }
sub short_date_format              { "\%y\/\%m\/\%d" }
sub date_parts_order               { $date_parts_order }



1;

