###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file rw.xml.
# The source file version number was 1.10, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::rw;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::rw::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Kuwa\ mbere",
"Kuwa\ kabiri",
"Kuwa\ gatatu",
"Kuwa\ kane",
"Kuwa\ gatanu",
"Kuwa\ gatandatu",
"Ku\ cyumweru",
);

my @day_abbreviations = (
"mbe\.",
"kab\.",
"gtu\.",
"kan\.",
"gnu\.",
"gnd\.",
"cyu\.",
);

my @month_names = (
"Mutarama",
"Gashyantare",
"Werurwe",
"Mata",
"Gicuransi",
"Kamena",
"Nyakanga",
"Kanama",
"Nzeli",
"Ukwakira",
"Ugushyingo",
"Ukuboza",
);

my @month_abbreviations = (
"mut\.",
"gas\.",
"wer\.",
"mat\.",
"gic\.",
"kam\.",
"nya\.",
"kan\.",
"nze\.",
"ukw\.",
"ugu\.",
"uku\.",
);

my @quarter_names = (
"igihembwe\ cya\ mbere",
"igihembwe\ cya\ kabiri",
"igihembwe\ cya\ gatatu",
"igihembwe\ cya\ kane",
);

my @quarter_abbreviations = (
"I1",
"I2",
"I3",
"I4",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }



1;

