###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file sr_Latn_BA.xml.
# The source file version number was 1.19, generated on
# 2006/06/28 01:23:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::sr_Latn_BA;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::sr_Latn;

@DateTime::Locale::sr_Latn_BA::ISA = qw(DateTime::Locale::sr_Latn);

my $date_parts_order = "ymd";


sub long_date_format               { "\%d\.\ \%B\ \%\{ce_year\}\." }
sub medium_date_format             { "\%\{ce_year\}\-\%m\-\%d" }
sub short_date_format              { "\%y\-\%m\-\%d" }
sub full_time_format               { "\%H\ časova\,\ \%M\ minuta\,\ \%S\ sekundi" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_parts_order               { $date_parts_order }



1;

