###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file sw.xml.
# The source file version number was 1.47, generated on
# 2006/07/07 21:00:33.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::sw;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::sw::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Jumatatu",
"Jumanne",
"Jumatano",
"Alhamisi",
"Ijumaa",
"Jumamosi",
"Jumapili",
);

my @day_abbreviations = (
"Jtt",
"Jnn",
"Jtn",
"Alh",
"Iju",
"Jmo",
"Jpi",
);

my @month_names = (
"Januari",
"Februari",
"Machi",
"Aprili",
"Mei",
"Juni",
"Julai",
"Agosti",
"Septemba",
"Oktoba",
"Novemba",
"Desemba",
);

my @month_abbreviations = (
"Jan",
"Feb",
"Mar",
"Apr",
"Mei",
"Jun",
"Jul",
"Ago",
"Sep",
"Okt",
"Nov",
"Des",
);

my @quarter_names = (
"robo\ ya\ kwanza",
"robo\ ya\ pili",
"robo\ ya\ tatu",
"robo\ ya\ nne",
);

my @quarter_abbreviations = (
"R1",
"R2",
"R3",
"R4",
);

my @era_names = (
"Kabla\ ya\ Kristo",
"Baada\ ya\ Kristo",
);

my @era_abbreviations = (
"KK",
"BK",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

