###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file syr.xml.
# The source file version number was 1.27, generated on
# 2006/06/24 23:27:01.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::syr;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::syr::ISA = qw(DateTime::Locale::root);

my @month_abbreviations = (
"܏ܟܢ ܏ܒ",
"ܫܒܛ",
"ܐܕܪ",
"ܢܝܣܢ",
"ܐܝܪ",
"ܚܙܝܪܢ",
"ܬܡܘܙ",
"ܐܒ",
"ܐܝܠܘܠ",
"܏ܬܫ ܏ܐ",
"܏ܬܫ ܏ܒ",
"܏ܟܢ ܏ܐ",
);



sub month_abbreviations            { \@month_abbreviations }



1;

