###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file th.xml.
# The source file version number was 1.75, generated on
# 2006/10/26 22:46:09.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::th;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::th::ISA = qw(DateTime::Locale::root);

my @day_names = (
"จันทร์",
"อังคาร",
"พุธ",
"พฤหัสบดี",
"ศุกร์",
"เสาร์",
"อาทิตย์",
);

my @day_abbreviations = (
"จ\.",
"อ\.",
"พ\.",
"พฤ\.",
"ศ\.",
"ส\.",
"อา\.",
);

my @day_narrows = (
"จ",
"อ",
"พ",
"พ",
"ศ",
"ส",
"อ",
);

my @month_names = (
"มกราคม",
"กุมภาพันธ์",
"มีนาคม",
"เมษายน",
"พฤษภาคม",
"มิถุนายน",
"กรกฎาคม",
"สิงหาคม",
"กันยายน",
"ตุลาคม",
"พฤศจิกายน",
"ธันวาคม",
);

my @month_abbreviations = (
"ม\.ค\.",
"ก\.พ\.",
"มี\.ค\.",
"เม\.ย\.",
"พ\.ค\.",
"มิ\.ย\.",
"ก\.ค\.",
"ส\.ค\.",
"ก\.ย\.",
"ต\.ค\.",
"พ\.ย\.",
"ธ\.ค\.",
);

my @month_narrows = (
"ม\.ค\.",
"ก\.พ\.",
"มี\.ค\.",
"เม\.ย\.",
"พ\.ค\.",
"มิ\.ย\.",
"ก\.ค\.",
"ส\.ค\.",
"ก\.ย\.",
"ต\.ค\.",
"พ\.ย\.",
"ธ\.ค\.",
);

my @quarter_names = (
"ไตรมาส\ 1",
"ไตรมาส\ 2",
"ไตรมาส\ 3",
"ไตรมาส\ 4",
);

my @era_names = (
"ปีก่อนคริสต์ศักราชที่",
"คริสต์ศักราช",
);

my @era_abbreviations = (
"ปีก่อน\ ค\.ศ\.\ ที่",
"ค\.ศ\.",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%Aที่\ \%\{day\}\ \%B\ \%\{era\}\ \%\{ce_year\}" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\ \%b\ \%\{ce_year\}" }
sub short_date_format              { "\%\{day\}\/\%\{month\}\/\%\{ce_year\}" }
sub full_time_format               { "\%\{hour\}\ นาฬิกา\ \%\{minute\}\ นาที\ \%S\ วินาที" }
sub long_time_format               { "\%\{hour\}\ นาฬิกา\ \%\{minute\}\ นาที" }
sub medium_time_format             { "\%\{hour\}\:\%M\:\%S" }
sub short_time_format              { "\%\{hour\}\:\%M" }
sub date_parts_order               { $date_parts_order }



1;

