###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ts.xml.
# The source file version number was 1.11, generated on
# 2006/06/28 02:08:34.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ts;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ts::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Musumbhunuku",
"Ravumbirhi",
"Ravunharhu",
"Ravumune",
"Ravuntlhanu",
"Mugqivela",
"Sonto",
);

my @day_abbreviations = (
"Mus",
"Bir",
"Har",
"Ne",
"Tlh",
"Mug",
"Son",
);

my @month_names = (
"Sunguti",
"Nyenyenyani",
"Nyenyankulu",
"Dzivamisoko",
"Mudyaxihi",
"Khotavuxika",
"Mawuwani",
"Mhawuri",
"Ndzhati",
"Nhlangula",
"Hukuri",
"N\'wendzamhala",
);

my @month_abbreviations = (
"Sun",
"Yan",
"Kul",
"Dzi",
"Mud",
"Kho",
"Maw",
"Mha",
"Ndz",
"Nhl",
"Huk",
"N\'w",
);

my @quarter_names = (
"Kotara\ yo\ sungula",
"Kotara\ ya\ vumbirhi",
"Kotara\ ya\ vunharhu",
"Kotara\ ya\ vumune",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);

my @era_names = (
"BC",
"AD",
);

my @era_abbreviations = (
"BC",
"AD",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

