###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file uz_Latn.xml.
# The source file version number was 1.13, generated on
# 2006/06/24 23:27:02.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::uz_Latn;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::uz;

@DateTime::Locale::uz_Latn::ISA = qw(DateTime::Locale::uz);

my @day_names = (
"dushanba",
"seshanba",
"chorshanba",
"payshanba",
"juma",
"shanba",
"yakshanba",
);

my @day_abbreviations = (
"Dush",
"Sesh",
"Chor",
"Pay",
"Jum",
"Shan",
"Yaksh",
);

my @day_narrows = (
"D",
"S",
"C",
"P",
"J",
"Sh",
"Y",
);

my @month_names = (
"Muharram",
"Safar",
"Rabiul\-avval",
"Rabiul\-oxir",
"Jumodiul\-ulo",
"Jumodiul\-uxro",
"Rajab",
"Shaʿbon",
"Ramazon",
"Shavvol",
"Zil\-qaʿda",
"Zil\-hijja",
);

my @month_abbreviations = (
"Yanv",
"Fev",
"Mar",
"Apr",
"May",
"Iyun",
"Iyul",
"Avg",
"Sen",
"Okt",
"Noya",
"Dek",
);

my @month_narrows = (
"Y",
"F",
"M",
"A",
"M",
"I",
"I",
"A",
"S",
"O",
"N",
"D",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }



1;

