###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ve.xml.
# The source file version number was 1.12, generated on
# 2006/06/29 15:44:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ve;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ve::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Musumbuluwo",
"Ḽavhuvhili",
"Ḽavhuraru",
"Ḽavhuṋa",
"Ḽavhuṱanu",
"Mugivhela",
"Swondaha",
);

my @day_abbreviations = (
"Mus",
"Vhi",
"Rar",
"Ṋa",
"Ṱan",
"Mug",
"Swo",
);

my @month_names = (
"Phando",
"Luhuhi",
"Ṱhafamuhwe",
"Lambamai",
"Shundunthule",
"Fulwi",
"Fulwana",
"Ṱhangule",
"Khubvumedzi",
"Tshimedzi",
"Ḽara",
"Nyendavhusiku",
);

my @month_abbreviations = (
"Pha",
"Luh",
"Thf",
"Lam",
"Shu",
"Lwi",
"Lwa",
"Ṱha",
"Khu",
"Tsh",
"Ḽar",
"Nye",
);

my @quarter_names = (
"Kotara\ ya\ u\ thoma",
"Kotara\ ya\ vhuvhili",
"Kotara\ ya\ vhuraru",
"Kotara\ ya\ vhuṋa",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);

my @era_names = (
"BC",
"AD",
);

my @era_abbreviations = (
"BC",
"AD",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

