###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file xh.xml.
# The source file version number was 1.11, generated on
# 2006/06/28 01:23:34.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::xh;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::xh::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Mvulo",
"Lwesibini",
"Lwesithathu",
"Lwesine",
"Lwesihlanu",
"Mgqibelo",
"Cawe",
);

my @day_abbreviations = (
"Mvu",
"Bin",
"Tha",
"Sin",
"Hla",
"Mgq",
"Caw",
);

my @month_names = (
"Janyuwari",
"Februwari",
"Matshi",
"Epreli",
"Meyi",
"Juni",
"Julayi",
"Agasti",
"Septemba",
"Okthoba",
"Novemba",
"Disemba",
);

my @month_abbreviations = (
"Jan",
"Feb",
"Mat",
"Epr",
"Mey",
"Jun",
"Jul",
"Aga",
"Sep",
"Okt",
"Nov",
"Dis",
);

my @quarter_names = (
"1\ unyangantathu",
"2\ unyangantathu",
"3\ unyangantathu",
"4\ unyangantathu",
);

my @era_names = (
"BC",
"umnyaka\ wokuzalwa\ kukaYesu",
);

my @era_abbreviations = (
"BC",
"AD",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

