###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file yo.xml.
# The source file version number was 1.13, generated on
# 2006/06/28 01:23:34.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::yo;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::yo::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Ojoaje",
"Ojoisegun",
"Ojoru",
"Ojobo",
"Ojoeti",
"Ojoabameta",
"Ojoaiku",
);

my @day_abbreviations = (
"Aje",
"Isegun",
"Ojoru",
"Ojobo",
"Eti",
"Abameta",
"Aiku",
);

my @month_names = (
"Osukini",
"Osukeji",
"Osuketa",
"Osukerin",
"Osukarun",
"Osukefa",
"Osukeje",
"Osukejo",
"Osukesan",
"Osukewa",
"Osukokanla",
"Osukejila",
);

my @month_abbreviations = (
"Sere",
"Erele",
"Erena",
"Igbe",
"Ebibi",
"Okudu",
"Agemo",
"Ogun",
"Owewe",
"Owara",
"Belu",
"Ope",
);

my @am_pms = (
"ARO",
"ALE",
);

my @era_names = (
"Saju\ Kristi",
"Lehin\ Kristi",
);

my @era_abbreviations = (
"SK",
"LK",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }



1;

