###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.03).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::LocaleCatalog;

use strict;

BEGIN
{
    if ($] >= 5.006)
    {
        require utf8; import utf8;
    }
}

@DateTime::Locale::Locales = (
    { id => "aa",
      en_language => "Afar",
      native_language => "Qafar",
    },
    { id => "aa_DJ",
      en_language => "Afar",
      en_territory => "Djibouti",
      native_language => "Qafar",
      native_territory => "Yabuuti",
      real_class => "aa",
    },
    { id => "aa_ER",
      en_language => "Afar",
      en_territory => "Eritrea",
      native_language => "Qafar",
      native_territory => "Eretria",
      real_class => "aa",
    },
    { id => "aa_ER_SAAHO",
      en_language => "Afar",
      en_territory => "Eritrea",
      en_variant => "Saaho",
      native_language => "Qafar",
      native_territory => "Eretria",
      native_variant => "Saaho",
    },
    { id => "aa_ET",
      en_language => "Afar",
      en_territory => "Ethiopia",
      native_language => "Qafar",
      native_territory => "Otobbia",
      real_class => "aa",
    },
    { id => "af",
      en_language => "Afrikaans",
      native_language => "Afrikaans",
    },
    { id => "af_NA",
      en_language => "Afrikaans",
      en_territory => "Namibia",
      native_language => "Afrikaans",
      native_territory => "Namibië",
      real_class => "af",
    },
    { id => "af_ZA",
      en_language => "Afrikaans",
      en_territory => "South\ Africa",
      native_language => "Afrikaans",
      native_territory => "Suid\-Afrika",
    },
    { id => "ak",
      en_language => "Akan",
      native_language => "Akan",
    },
    { id => "ak_GH",
      en_language => "Akan",
      en_territory => "Ghana",
      native_language => "Akan",
      native_territory => "Ghana",
      real_class => "ak",
    },
    { id => "am",
      en_language => "Amharic",
      native_language => "አማርኛ",
    },
    { id => "am_ET",
      en_language => "Amharic",
      en_territory => "Ethiopia",
      native_language => "አማርኛ",
      native_territory => "ኢትዮጵያ",
    },
    { id => "ar",
      en_language => "Arabic",
      native_language => "العربية",
    },
    { id => "ar_AE",
      en_language => "Arabic",
      en_territory => "United\ Arab\ Emirates",
      native_language => "العربية",
      native_territory => "الامارات\ العربية\ المتحدة",
      real_class => "ar",
    },
    { id => "ar_BH",
      en_language => "Arabic",
      en_territory => "Bahrain",
      native_language => "العربية",
      native_territory => "البحرين",
      real_class => "ar",
    },
    { id => "ar_DZ",
      en_language => "Arabic",
      en_territory => "Algeria",
      native_language => "العربية",
      native_territory => "الجزائر",
      real_class => "ar",
    },
    { id => "ar_EG",
      en_language => "Arabic",
      en_territory => "Egypt",
      native_language => "العربية",
      native_territory => "مصر",
    },
    { id => "ar_IQ",
      en_language => "Arabic",
      en_territory => "Iraq",
      native_language => "العربية",
      native_territory => "العراق",
      real_class => "ar",
    },
    { id => "ar_JO",
      en_language => "Arabic",
      en_territory => "Jordan",
      native_language => "العربية",
      native_territory => "الأردن",
    },
    { id => "ar_KW",
      en_language => "Arabic",
      en_territory => "Kuwait",
      native_language => "العربية",
      native_territory => "الكويت",
      real_class => "ar",
    },
    { id => "ar_LB",
      en_language => "Arabic",
      en_territory => "Lebanon",
      native_language => "العربية",
      native_territory => "لبنان",
    },
    { id => "ar_LY",
      en_language => "Arabic",
      en_territory => "Libya",
      native_language => "العربية",
      native_territory => "ليبيا",
      real_class => "ar",
    },
    { id => "ar_MA",
      en_language => "Arabic",
      en_territory => "Morocco",
      native_language => "العربية",
      native_territory => "المغرب",
      real_class => "ar",
    },
    { id => "ar_OM",
      en_language => "Arabic",
      en_territory => "Oman",
      native_language => "العربية",
      native_territory => "عمان",
      real_class => "ar",
    },
    { id => "ar_QA",
      en_language => "Arabic",
      en_territory => "Qatar",
      native_language => "العربية",
      native_territory => "قطر",
    },
    { id => "ar_SA",
      en_language => "Arabic",
      en_territory => "Saudi\ Arabia",
      native_language => "العربية",
      native_territory => "المملكة\ العربية\ السعودية",
    },
    { id => "ar_SD",
      en_language => "Arabic",
      en_territory => "Sudan",
      native_language => "العربية",
      native_territory => "السودان",
      real_class => "ar",
    },
    { id => "ar_SY",
      en_language => "Arabic",
      en_territory => "Syria",
      native_language => "العربية",
      native_territory => "سوريا",
    },
    { id => "ar_TN",
      en_language => "Arabic",
      en_territory => "Tunisia",
      native_language => "العربية",
      native_territory => "تونس",
    },
    { id => "ar_YE",
      en_language => "Arabic",
      en_territory => "Yemen",
      native_language => "العربية",
      native_territory => "اليمن",
    },
    { id => "as",
      en_language => "Assamese",
      native_language => "অসমীয়া",
    },
    { id => "as_IN",
      en_language => "Assamese",
      en_territory => "India",
      native_language => "অসমীয়া",
      native_territory => "ভাৰত",
    },
    { id => "az",
      en_language => "Azerbaijani",
      native_language => "Азәрбајҹан",
    },
    { id => "az_AZ",
      en_language => "Azerbaijani",
      en_territory => "Azerbaijan",
      native_language => "Азәрбајҹан",
      native_territory => "Азәрбајҹан",
      real_class => "az",
    },
    { id => "az_Cyrl",
      en_language => "Azerbaijani",
      en_script => "Cyrillic",
      native_language => "Азәрбајҹан",
      native_script => "Cyrillic",
    },
    { id => "az_Cyrl_AZ",
      en_language => "Azerbaijani",
      en_script => "Cyrillic",
      en_territory => "Azerbaijan",
      native_language => "Азәрбајҹан",
      native_script => "Cyrillic",
      native_territory => "Азәрбајҹан",
      real_class => "az_Cyrl",
    },
    { id => "az_Latn",
      en_language => "Azerbaijani",
      en_script => "Latin",
      native_language => "Азәрбајҹан",
      native_script => "Latin",
      real_class => "az",
    },
    { id => "az_Latn_AZ",
      en_language => "Azerbaijani",
      en_script => "Latin",
      en_territory => "Azerbaijan",
      native_language => "Азәрбајҹан",
      native_script => "Latin",
      native_territory => "Азәрбајҹан",
      real_class => "az",
    },
    { id => "be",
      en_language => "Belarusian",
      native_language => "Беларускі",
    },
    { id => "be_BY",
      en_language => "Belarusian",
      en_territory => "Belarus",
      native_language => "Беларускі",
      native_territory => "Беларусь",
      real_class => "be",
    },
    { id => "bg",
      en_language => "Bulgarian",
      native_language => "Български",
    },
    { id => "bg_BG",
      en_language => "Bulgarian",
      en_territory => "Bulgaria",
      native_language => "Български",
      native_territory => "България",
    },
    { id => "bn",
      en_language => "Bengali",
      native_language => "বাংলা",
    },
    { id => "bn_BD",
      en_language => "Bengali",
      en_territory => "Bangladesh",
      native_language => "বাংলা",
      native_territory => "বাংলাদেশ",
    },
    { id => "bn_IN",
      en_language => "Bengali",
      en_territory => "India",
      native_language => "বাংলা",
      native_territory => "ভারত",
    },
    { id => "bs",
      en_language => "Bosnian",
      native_language => "Bosnian",
    },
    { id => "bs_BA",
      en_language => "Bosnian",
      en_territory => "Bosnia\ and\ Herzegovina",
      native_language => "Bosnian",
      native_territory => "Bosnia\ and\ Herzegovina",
      real_class => "bs",
    },
    { id => "byn",
      en_language => "Blin",
      native_language => "ብሊን",
    },
    { id => "byn_ER",
      en_language => "Blin",
      en_territory => "Eritrea",
      native_language => "ብሊን",
      native_territory => "ኤርትራ",
    },
    { id => "ca",
      en_language => "Catalan",
      native_language => "català",
    },
    { id => "ca_ES",
      en_language => "Catalan",
      en_territory => "Spain",
      native_language => "català",
      native_territory => "Espanya",
      real_class => "ca",
    },
    { id => "cch",
      en_language => "Atsam",
      native_language => "Atsam",
    },
    { id => "cch_NG",
      en_language => "Atsam",
      en_territory => "Nigeria",
      native_language => "Atsam",
      native_territory => "Nigeria",
      real_class => "cch",
    },
    { id => "cs",
      en_language => "Czech",
      native_language => "Čeština",
    },
    { id => "cs_CZ",
      en_language => "Czech",
      en_territory => "Czech\ Republic",
      native_language => "Čeština",
      native_territory => "Česká\ republika",
      real_class => "cs",
    },
    { id => "cy",
      en_language => "Welsh",
      native_language => "Cymraeg",
    },
    { id => "cy_GB",
      en_language => "Welsh",
      en_territory => "United\ Kingdom",
      native_language => "Cymraeg",
      native_territory => "Prydain\ Fawr",
    },
    { id => "da",
      en_language => "Danish",
      native_language => "Dansk",
    },
    { id => "da_DK",
      en_language => "Danish",
      en_territory => "Denmark",
      native_language => "Dansk",
      native_territory => "Danmark",
      real_class => "da",
    },
    { id => "de",
      en_language => "German",
      native_language => "Deutsch",
    },
    { id => "de_AT",
      en_language => "German",
      en_territory => "Austria",
      native_language => "Deutsch",
      native_territory => "Österreich",
    },
    { id => "de_BE",
      en_language => "German",
      en_territory => "Belgium",
      native_language => "Deutsch",
      native_territory => "Belgien",
    },
    { id => "de_CH",
      en_language => "German",
      en_territory => "Switzerland",
      native_language => "Deutsch",
      native_territory => "Schweiz",
      real_class => "de",
    },
    { id => "de_DE",
      en_language => "German",
      en_territory => "Germany",
      native_language => "Deutsch",
      native_territory => "Deutschland",
      real_class => "de",
    },
    { id => "de_LI",
      en_language => "German",
      en_territory => "Liechtenstein",
      native_language => "Deutsch",
      native_territory => "Liechtenstein",
      real_class => "de",
    },
    { id => "de_LU",
      en_language => "German",
      en_territory => "Luxembourg",
      native_language => "Deutsch",
      native_territory => "Luxemburg",
      real_class => "de",
    },
    { id => "dz",
      en_language => "Dzongkha",
      native_language => "རྫོང་ཁ",
    },
    { id => "dz_BT",
      en_language => "Dzongkha",
      en_territory => "Bhutan",
      native_language => "རྫོང་ཁ",
      native_territory => "འབྲུག",
      real_class => "dz",
    },
    { id => "ee",
      en_language => "Ewe",
      native_language => "Ewe",
    },
    { id => "ee_GH",
      en_language => "Ewe",
      en_territory => "Ghana",
      native_language => "Ewe",
      native_territory => "Ghana",
      real_class => "ee",
    },
    { id => "ee_TG",
      en_language => "Ewe",
      en_territory => "Togo",
      native_language => "Ewe",
      native_territory => "Togo",
      real_class => "ee",
    },
    { id => "el",
      en_language => "Greek",
      native_language => "Ἑλληνικά",
    },
    { id => "el_CY",
      en_language => "Greek",
      en_territory => "Cyprus",
      native_language => "Ἑλληνικά",
      native_territory => "Κύπρος",
      real_class => "el",
    },
    { id => "el_GR",
      en_language => "Greek",
      en_territory => "Greece",
      native_language => "Ἑλληνικά",
      native_territory => "Ἑλλάδα",
      real_class => "el",
    },
    { id => "el_POLYTONI",
      en_language => "Greek",
      native_language => "Ἑλληνικά",
      real_class => "el",
    },
    { id => "en",
      en_language => "English",
      native_language => "English",
    },
    { id => "en_AS",
      en_language => "English",
      en_territory => "American\ Samoa",
      native_language => "English",
      native_territory => "American\ Samoa",
      real_class => "en",
    },
    { id => "en_AU",
      en_language => "English",
      en_territory => "Australia",
      native_language => "English",
      native_territory => "Australia",
    },
    { id => "en_BE",
      en_language => "English",
      en_territory => "Belgium",
      native_language => "English",
      native_territory => "Belgium",
    },
    { id => "en_BW",
      en_language => "English",
      en_territory => "Botswana",
      native_language => "English",
      native_territory => "Botswana",
    },
    { id => "en_BZ",
      en_language => "English",
      en_territory => "Belize",
      native_language => "English",
      native_territory => "Belize",
    },
    { id => "en_CA",
      en_language => "English",
      en_territory => "Canada",
      native_language => "English",
      native_territory => "Canada",
    },
    { id => "en_GB",
      en_language => "English",
      en_territory => "United\ Kingdom",
      native_language => "English",
      native_territory => "United\ Kingdom",
    },
    { id => "en_GU",
      en_language => "English",
      en_territory => "Guam",
      native_language => "English",
      native_territory => "Guam",
      real_class => "en",
    },
    { id => "en_HK",
      en_language => "English",
      en_territory => "Hong\ Kong\ SAR\ China",
      native_language => "English",
      native_territory => "Hong\ Kong\ SAR\ China",
    },
    { id => "en_IE",
      en_language => "English",
      en_territory => "Ireland",
      native_language => "English",
      native_territory => "Ireland",
    },
    { id => "en_IN",
      en_language => "English",
      en_territory => "India",
      native_language => "English",
      native_territory => "India",
    },
    { id => "en_JM",
      en_language => "English",
      en_territory => "Jamaica",
      native_language => "English",
      native_territory => "Jamaica",
      real_class => "en",
    },
    { id => "en_MH",
      en_language => "English",
      en_territory => "Marshall\ Islands",
      native_language => "English",
      native_territory => "Marshall\ Islands",
      real_class => "en",
    },
    { id => "en_MP",
      en_language => "English",
      en_territory => "Northern\ Mariana\ Islands",
      native_language => "English",
      native_territory => "Northern\ Mariana\ Islands",
      real_class => "en",
    },
    { id => "en_MT",
      en_language => "English",
      en_territory => "Malta",
      native_language => "English",
      native_territory => "Malta",
    },
    { id => "en_NA",
      en_language => "English",
      en_territory => "Namibia",
      native_language => "English",
      native_territory => "Namibia",
      real_class => "en",
    },
    { id => "en_NZ",
      en_language => "English",
      en_territory => "New\ Zealand",
      native_language => "English",
      native_territory => "New\ Zealand",
    },
    { id => "en_PH",
      en_language => "English",
      en_territory => "Philippines",
      native_language => "English",
      native_territory => "Philippines",
    },
    { id => "en_PK",
      en_language => "English",
      en_territory => "Pakistan",
      native_language => "English",
      native_territory => "Pakistan",
    },
    { id => "en_SG",
      en_language => "English",
      en_territory => "Singapore",
      native_language => "English",
      native_territory => "Singapore",
    },
    { id => "en_TT",
      en_language => "English",
      en_territory => "Trinidad\ and\ Tobago",
      native_language => "English",
      native_territory => "Trinidad\ and\ Tobago",
      real_class => "en",
    },
    { id => "en_UM",
      en_language => "English",
      en_territory => "United\ States\ Minor\ Outlying\ Islands",
      native_language => "English",
      native_territory => "United\ States\ Minor\ Outlying\ Islands",
      real_class => "en",
    },
    { id => "en_US",
      en_language => "English",
      en_territory => "United\ States",
      native_language => "English",
      native_territory => "United\ States",
      real_class => "en",
    },
    { id => "en_US_POSIX",
      en_language => "English",
      en_territory => "United\ States",
      en_variant => "Posix",
      native_language => "English",
      native_territory => "United\ States",
      native_variant => "Posix",
      real_class => "en",
    },
    { id => "en_VI",
      en_language => "English",
      en_territory => "U\.S\.\ Virgin\ Islands",
      native_language => "English",
      native_territory => "U\.S\.\ Virgin\ Islands",
      real_class => "en",
    },
    { id => "en_ZA",
      en_language => "English",
      en_territory => "South\ Africa",
      native_language => "English",
      native_territory => "South\ Africa",
    },
    { id => "en_ZW",
      en_language => "English",
      en_territory => "Zimbabwe",
      native_language => "English",
      native_territory => "Zimbabwe",
    },
    { id => "eo",
      en_language => "Esperanto",
      native_language => "esperanto",
    },
    { id => "es",
      en_language => "Spanish",
      native_language => "español",
    },
    { id => "es_AR",
      en_language => "Spanish",
      en_territory => "Argentina",
      native_language => "español",
      native_territory => "Argentina",
    },
    { id => "es_BO",
      en_language => "Spanish",
      en_territory => "Bolivia",
      native_language => "español",
      native_territory => "Bolivia",
    },
    { id => "es_CL",
      en_language => "Spanish",
      en_territory => "Chile",
      native_language => "español",
      native_territory => "Chile",
    },
    { id => "es_CO",
      en_language => "Spanish",
      en_territory => "Colombia",
      native_language => "español",
      native_territory => "Colombia",
    },
    { id => "es_CR",
      en_language => "Spanish",
      en_territory => "Costa\ Rica",
      native_language => "español",
      native_territory => "Costa\ Rica",
    },
    { id => "es_DO",
      en_language => "Spanish",
      en_territory => "Dominican\ Republic",
      native_language => "español",
      native_territory => "República\ Dominicana",
    },
    { id => "es_EC",
      en_language => "Spanish",
      en_territory => "Ecuador",
      native_language => "español",
      native_territory => "Ecuador",
    },
    { id => "es_ES",
      en_language => "Spanish",
      en_territory => "Spain",
      native_language => "español",
      native_territory => "España",
    },
    { id => "es_GT",
      en_language => "Spanish",
      en_territory => "Guatemala",
      native_language => "español",
      native_territory => "Guatemala",
    },
    { id => "es_HN",
      en_language => "Spanish",
      en_territory => "Honduras",
      native_language => "español",
      native_territory => "Honduras",
    },
    { id => "es_MX",
      en_language => "Spanish",
      en_territory => "Mexico",
      native_language => "español",
      native_territory => "México",
    },
    { id => "es_NI",
      en_language => "Spanish",
      en_territory => "Nicaragua",
      native_language => "español",
      native_territory => "Nicaragua",
    },
    { id => "es_PA",
      en_language => "Spanish",
      en_territory => "Panama",
      native_language => "español",
      native_territory => "Panamá",
    },
    { id => "es_PE",
      en_language => "Spanish",
      en_territory => "Peru",
      native_language => "español",
      native_territory => "Perú",
      real_class => "es",
    },
    { id => "es_PR",
      en_language => "Spanish",
      en_territory => "Puerto\ Rico",
      native_language => "español",
      native_territory => "Puerto\ Rico",
    },
    { id => "es_PY",
      en_language => "Spanish",
      en_territory => "Paraguay",
      native_language => "español",
      native_territory => "Paraguay",
    },
    { id => "es_SV",
      en_language => "Spanish",
      en_territory => "El\ Salvador",
      native_language => "español",
      native_territory => "El\ Salvador",
    },
    { id => "es_US",
      en_language => "Spanish",
      en_territory => "United\ States",
      native_language => "español",
      native_territory => "Estados\ Unidos",
    },
    { id => "es_UY",
      en_language => "Spanish",
      en_territory => "Uruguay",
      native_language => "español",
      native_territory => "Uruguay",
    },
    { id => "es_VE",
      en_language => "Spanish",
      en_territory => "Venezuela",
      native_language => "español",
      native_territory => "Venezuela",
    },
    { id => "et",
      en_language => "Estonian",
      native_language => "Eesti",
    },
    { id => "et_EE",
      en_language => "Estonian",
      en_territory => "Estonia",
      native_language => "Eesti",
      native_territory => "Eesti",
    },
    { id => "eu",
      en_language => "Basque",
      native_language => "euskara",
    },
    { id => "eu_ES",
      en_language => "Basque",
      en_territory => "Spain",
      native_language => "euskara",
      native_territory => "Espainia",
    },
    { id => "fi",
      en_language => "Finnish",
      native_language => "suomi",
    },
    { id => "fi_FI",
      en_language => "Finnish",
      en_territory => "Finland",
      native_language => "suomi",
      native_territory => "Suomi",
      real_class => "fi",
    },
    { id => "fo",
      en_language => "Faroese",
      native_language => "føroyskt",
    },
    { id => "fo_FO",
      en_language => "Faroese",
      en_territory => "Faroe\ Islands",
      native_language => "føroyskt",
      native_territory => "Føroyar",
      real_class => "fo",
    },
    { id => "fr",
      en_language => "French",
      native_language => "français",
    },
    { id => "fr_BE",
      en_language => "French",
      en_territory => "Belgium",
      native_language => "français",
      native_territory => "Belgique",
    },
    { id => "fr_CA",
      en_language => "French",
      en_territory => "Canada",
      native_language => "français",
      native_territory => "Canada",
    },
    { id => "fr_CH",
      en_language => "French",
      en_territory => "Switzerland",
      native_language => "français",
      native_territory => "Suisse",
    },
    { id => "fr_FR",
      en_language => "French",
      en_territory => "France",
      native_language => "français",
      native_territory => "France",
      real_class => "fr",
    },
    { id => "fr_LU",
      en_language => "French",
      en_territory => "Luxembourg",
      native_language => "français",
      native_territory => "Luxembourg",
      real_class => "fr",
    },
    { id => "fr_MC",
      en_language => "French",
      en_territory => "Monaco",
      native_language => "français",
      native_territory => "Monaco",
      real_class => "fr",
    },
    { id => "fur",
      en_language => "Friulian",
      native_language => "furlan",
    },
    { id => "fur_IT",
      en_language => "Friulian",
      en_territory => "Italy",
      native_language => "furlan",
      native_territory => "Italie",
      real_class => "fur",
    },
    { id => "ga",
      en_language => "Irish",
      native_language => "Gaeilge",
    },
    { id => "ga_IE",
      en_language => "Irish",
      en_territory => "Ireland",
      native_language => "Gaeilge",
      native_territory => "Éire",
    },
    { id => "gaa",
      en_language => "Ga",
      native_language => "Ga",
    },
    { id => "gaa_GH",
      en_language => "Ga",
      en_territory => "Ghana",
      native_language => "Ga",
      native_territory => "Ghana",
      real_class => "gaa",
    },
    { id => "gez",
      en_language => "Geez",
      native_language => "ግዕዝኛ",
    },
    { id => "gez_ER",
      en_language => "Geez",
      en_territory => "Eritrea",
      native_language => "ግዕዝኛ",
      native_territory => "ኤርትራ",
    },
    { id => "gez_ET",
      en_language => "Geez",
      en_territory => "Ethiopia",
      native_language => "ግዕዝኛ",
      native_territory => "ኢትዮጵያ",
    },
    { id => "gl",
      en_language => "Galician",
      native_language => "galego",
    },
    { id => "gl_ES",
      en_language => "Galician",
      en_territory => "Spain",
      native_language => "galego",
      native_territory => "España",
    },
    { id => "gu",
      en_language => "Gujarati",
      native_language => "ગુજરાતી",
    },
    { id => "gu_IN",
      en_language => "Gujarati",
      en_territory => "India",
      native_language => "ગુજરાતી",
      native_territory => "ભારત",
    },
    { id => "gv",
      en_language => "Manx",
      native_language => "Gaelg",
    },
    { id => "gv_GB",
      en_language => "Manx",
      en_territory => "United\ Kingdom",
      native_language => "Gaelg",
      native_territory => "Rywvaneth\ Unys",
    },
    { id => "ha",
      en_language => "Hausa",
      native_language => "Hausa",
    },
    { id => "ha_Arab",
      en_language => "Hausa",
      en_script => "Arabic",
      native_language => "Hausa",
      native_script => "Arabic",
    },
    { id => "ha_Arab_NG",
      en_language => "Hausa",
      en_script => "Arabic",
      en_territory => "Nigeria",
      native_language => "Hausa",
      native_script => "Arabic",
      native_territory => "Nigeria",
      real_class => "ha_Arab",
    },
    { id => "ha_GH",
      en_language => "Hausa",
      en_territory => "Ghana",
      native_language => "Hausa",
      native_territory => "Ghana",
      real_class => "ha",
    },
    { id => "ha_Latn",
      en_language => "Hausa",
      en_script => "Latin",
      native_language => "Hausa",
      native_script => "Latin",
      real_class => "ha",
    },
    { id => "ha_Latn_GH",
      en_language => "Hausa",
      en_script => "Latin",
      en_territory => "Ghana",
      native_language => "Hausa",
      native_script => "Latin",
      native_territory => "Ghana",
      real_class => "ha",
    },
    { id => "ha_Latn_NE",
      en_language => "Hausa",
      en_script => "Latin",
      en_territory => "Niger",
      native_language => "Hausa",
      native_script => "Latin",
      native_territory => "Niger",
      real_class => "ha",
    },
    { id => "ha_Latn_NG",
      en_language => "Hausa",
      en_script => "Latin",
      en_territory => "Nigeria",
      native_language => "Hausa",
      native_script => "Latin",
      native_territory => "Nigeria",
      real_class => "ha",
    },
    { id => "ha_NE",
      en_language => "Hausa",
      en_territory => "Niger",
      native_language => "Hausa",
      native_territory => "Niger",
      real_class => "ha",
    },
    { id => "ha_NG",
      en_language => "Hausa",
      en_territory => "Nigeria",
      native_language => "Hausa",
      native_territory => "Nigeria",
      real_class => "ha",
    },
    { id => "haw",
      en_language => "Hawaiian",
      native_language => "ʻōlelo\ Hawaiʻi",
    },
    { id => "haw_US",
      en_language => "Hawaiian",
      en_territory => "United\ States",
      native_language => "ʻōlelo\ Hawaiʻi",
      native_territory => "ʻAmelika\ Hui\ Pū\ ʻIa",
    },
    { id => "he",
      en_language => "Hebrew",
      native_language => "עברית",
    },
    { id => "he_IL",
      en_language => "Hebrew",
      en_territory => "Israel",
      native_language => "עברית",
      native_territory => "ישראל",
      real_class => "he",
    },
    { id => "hi",
      en_language => "Hindi",
      native_language => "हिंदी",
    },
    { id => "hi_IN",
      en_language => "Hindi",
      en_territory => "India",
      native_language => "हिंदी",
      native_territory => "भारत",
    },
    { id => "hr",
      en_language => "Croatian",
      native_language => "hrvatski",
    },
    { id => "hr_HR",
      en_language => "Croatian",
      en_territory => "Croatia",
      native_language => "hrvatski",
      native_territory => "Hrvatska",
      real_class => "hr",
    },
    { id => "hu",
      en_language => "Hungarian",
      native_language => "magyar",
    },
    { id => "hu_HU",
      en_language => "Hungarian",
      en_territory => "Hungary",
      native_language => "magyar",
      native_territory => "Magyarország",
      real_class => "hu",
    },
    { id => "hy",
      en_language => "Armenian",
      native_language => "Հայերէն",
    },
    { id => "hy_AM",
      en_language => "Armenian",
      en_territory => "Armenia",
      native_language => "Հայերէն",
      native_territory => "Հայաստանի\ Հանրապետութիւն",
    },
    { id => "hy_AM_REVISED",
      en_language => "Armenian",
      en_territory => "Armenia",
      en_variant => "Revised",
      native_language => "Հայերէն",
      native_territory => "Հայաստանի\ Հանրապետութիւն",
      native_variant => "Revised",
    },
    { id => "ia",
      en_language => "Interlingua",
      native_language => "Interlingua",
    },
    { id => "id",
      en_language => "Indonesian",
      native_language => "Bahasa\ Indonesia",
    },
    { id => "id_ID",
      en_language => "Indonesian",
      en_territory => "Indonesia",
      native_language => "Bahasa\ Indonesia",
      native_territory => "Indonesia",
    },
    { id => "ig",
      en_language => "Igbo",
      native_language => "Igbo",
    },
    { id => "ig_NG",
      en_language => "Igbo",
      en_territory => "Nigeria",
      native_language => "Igbo",
      native_territory => "Nigeria",
      real_class => "ig",
    },
    { id => "is",
      en_language => "Icelandic",
      native_language => "Íslenska",
    },
    { id => "is_IS",
      en_language => "Icelandic",
      en_territory => "Iceland",
      native_language => "Íslenska",
      native_territory => "Ísland",
      real_class => "is",
    },
    { id => "it",
      en_language => "Italian",
      native_language => "italiano",
    },
    { id => "it_CH",
      en_language => "Italian",
      en_territory => "Switzerland",
      native_language => "italiano",
      native_territory => "Svizzera",
    },
    { id => "it_IT",
      en_language => "Italian",
      en_territory => "Italy",
      native_language => "italiano",
      native_territory => "Italia",
    },
    { id => "iu",
      en_language => "Inuktitut",
      native_language => "ᐃᓄᒃᑎᑐᑦ\ ᑎᑎᕋᐅᓯᖅ",
    },
    { id => "ja",
      en_language => "Japanese",
      native_language => "日本語",
    },
    { id => "ja_JP",
      en_language => "Japanese",
      en_territory => "Japan",
      native_language => "日本語",
      native_territory => "日本",
      real_class => "ja",
    },
    { id => "ka",
      en_language => "Georgian",
      native_language => "ქართული",
    },
    { id => "ka_GE",
      en_language => "Georgian",
      en_territory => "Georgia",
      native_language => "ქართული",
      native_territory => "საქართველო",
      real_class => "ka",
    },
    { id => "kaj",
      en_language => "Jju",
      native_language => "Jju",
    },
    { id => "kaj_NG",
      en_language => "Jju",
      en_territory => "Nigeria",
      native_language => "Jju",
      native_territory => "Nigeria",
      real_class => "kaj",
    },
    { id => "kam",
      en_language => "Kamba",
      native_language => "Kamba",
    },
    { id => "kam_KE",
      en_language => "Kamba",
      en_territory => "Kenya",
      native_language => "Kamba",
      native_territory => "Kenya",
      real_class => "kam",
    },
    { id => "kcg",
      en_language => "Tyap",
      native_language => "Tyap",
    },
    { id => "kcg_NG",
      en_language => "Tyap",
      en_territory => "Nigeria",
      native_language => "Tyap",
      native_territory => "Nigeria",
      real_class => "kcg",
    },
    { id => "kfo",
      en_language => "Koro",
      native_language => "Koro",
    },
    { id => "kfo_NG",
      en_language => "Koro",
      en_territory => "Nigeria",
      native_language => "Koro",
      native_territory => "Nigeria",
      real_class => "kfo",
    },
    { id => "kk",
      en_language => "Kazakh",
      native_language => "Қазақ",
    },
    { id => "kk_KZ",
      en_language => "Kazakh",
      en_territory => "Kazakhstan",
      native_language => "Қазақ",
      native_territory => "Қазақстан",
      real_class => "kk",
    },
    { id => "kl",
      en_language => "Kalaallisut",
      native_language => "kalaallisut",
    },
    { id => "kl_GL",
      en_language => "Kalaallisut",
      en_territory => "Greenland",
      native_language => "kalaallisut",
      native_territory => "Kalaallit\ Nunaat",
    },
    { id => "km",
      en_language => "Khmer",
      native_language => "ភាសាខ្មែរ",
    },
    { id => "km_KH",
      en_language => "Khmer",
      en_territory => "Cambodia",
      native_language => "ភាសាខ្មែរ",
      native_territory => "កម្ពុជា",
      real_class => "km",
    },
    { id => "kn",
      en_language => "Kannada",
      native_language => "ಕನ್ನಡ",
    },
    { id => "kn_IN",
      en_language => "Kannada",
      en_territory => "India",
      native_language => "ಕನ್ನಡ",
      native_territory => "ಭಾರತ",
    },
    { id => "ko",
      en_language => "Korean",
      native_language => "한국어",
    },
    { id => "ko_KR",
      en_language => "Korean",
      en_territory => "South\ Korea",
      native_language => "한국어",
      native_territory => "대한민국",
    },
    { id => "kok",
      en_language => "Konkani",
      native_language => "कोंकणी",
    },
    { id => "kok_IN",
      en_language => "Konkani",
      en_territory => "India",
      native_language => "कोंकणी",
      native_territory => "भारत",
    },
    { id => "kw",
      en_language => "Cornish",
      native_language => "kernewek",
    },
    { id => "kw_GB",
      en_language => "Cornish",
      en_territory => "United\ Kingdom",
      native_language => "kernewek",
      native_territory => "Rywvaneth\ Unys",
    },
    { id => "ln",
      en_language => "Lingala",
      native_language => "lingála",
    },
    { id => "ln_CD",
      en_language => "Lingala",
      en_territory => "Congo\ \(Kinshasa\)",
      native_language => "lingála",
      native_territory => "Kɔngɔ́\ \(Kinshasa\)",
      real_class => "ln",
    },
    { id => "ln_CG",
      en_language => "Lingala",
      en_territory => "Congo\ \(Brazzaville\)",
      native_language => "lingála",
      native_territory => "Kɔngɔ́\ \(Brazzaville\)",
      real_class => "ln",
    },
    { id => "lo",
      en_language => "Lao",
      native_language => "ລາວ",
    },
    { id => "lo_LA",
      en_language => "Lao",
      en_territory => "Laos",
      native_language => "ລາວ",
      native_territory => "ລາວ",
      real_class => "lo",
    },
    { id => "lt",
      en_language => "Lithuanian",
      native_language => "Lietuvių",
    },
    { id => "lt_LT",
      en_language => "Lithuanian",
      en_territory => "Lithuania",
      native_language => "Lietuvių",
      native_territory => "Lietuva",
      real_class => "lt",
    },
    { id => "lv",
      en_language => "Latvian",
      native_language => "latviešu",
    },
    { id => "lv_LV",
      en_language => "Latvian",
      en_territory => "Latvia",
      native_language => "latviešu",
      native_territory => "Latvija",
      real_class => "lv",
    },
    { id => "mk",
      en_language => "Macedonian",
      native_language => "македонски",
    },
    { id => "mk_MK",
      en_language => "Macedonian",
      en_territory => "Macedonia",
      native_language => "македонски",
      native_territory => "Македонија",
      real_class => "mk",
    },
    { id => "ml",
      en_language => "Malayalam",
      native_language => "മലയാളം",
    },
    { id => "ml_IN",
      en_language => "Malayalam",
      en_territory => "India",
      native_language => "മലയാളം",
      native_territory => "ഇന്ത്യ",
    },
    { id => "mn",
      en_language => "Mongolian",
      native_language => "Монгол\ хэл",
    },
    { id => "mn_MN",
      en_language => "Mongolian",
      en_territory => "Mongolia",
      native_language => "Монгол\ хэл",
      native_territory => "Монгол\ улс",
      real_class => "mn",
    },
    { id => "mr",
      en_language => "Marathi",
      native_language => "मराठी",
    },
    { id => "mr_IN",
      en_language => "Marathi",
      en_territory => "India",
      native_language => "मराठी",
      native_territory => "भारत",
    },
    { id => "ms",
      en_language => "Malay",
      native_language => "Bahasa\ Melayu",
    },
    { id => "ms_BN",
      en_language => "Malay",
      en_territory => "Brunei",
      native_language => "Bahasa\ Melayu",
      native_territory => "Brunei",
    },
    { id => "ms_MY",
      en_language => "Malay",
      en_territory => "Malaysia",
      native_language => "Bahasa\ Melayu",
      native_territory => "Malaysia",
    },
    { id => "mt",
      en_language => "Maltese",
      native_language => "Malti",
    },
    { id => "mt_MT",
      en_language => "Maltese",
      en_territory => "Malta",
      native_language => "Malti",
      native_territory => "Malta",
      real_class => "mt",
    },
    { id => "nb",
      en_language => "Norwegian\ Bokmål",
      native_language => "bokmål",
    },
    { id => "nb_NO",
      en_language => "Norwegian\ Bokmål",
      en_territory => "Norway",
      native_language => "bokmål",
      native_territory => "Norge",
      real_class => "nb",
    },
    { id => "ne",
      en_language => "Nepali",
      native_language => "Nepali",
    },
    { id => "ne_NP",
      en_language => "Nepali",
      en_territory => "Nepal",
      native_language => "Nepali",
      native_territory => "Nepal",
      real_class => "ne",
    },
    { id => "nl",
      en_language => "Dutch",
      native_language => "Nederlands",
    },
    { id => "nl_BE",
      en_language => "Dutch",
      en_territory => "Belgium",
      native_language => "Nederlands",
      native_territory => "België",
    },
    { id => "nl_NL",
      en_language => "Dutch",
      en_territory => "Netherlands",
      native_language => "Nederlands",
      native_territory => "Nederland",
      real_class => "nl",
    },
    { id => "nn",
      en_language => "Norwegian\ Nynorsk",
      native_language => "nynorsk",
    },
    { id => "nn_NO",
      en_language => "Norwegian\ Nynorsk",
      en_territory => "Norway",
      native_language => "nynorsk",
      native_territory => "Noreg",
      real_class => "nn",
    },
    { id => "nr",
      en_language => "South\ Ndebele",
      native_language => "South\ Ndebele",
    },
    { id => "nr_ZA",
      en_language => "South\ Ndebele",
      en_territory => "South\ Africa",
      native_language => "South\ Ndebele",
      native_territory => "South\ Africa",
      real_class => "nr",
    },
    { id => "nso",
      en_language => "Northern\ Sotho",
      native_language => "Northern\ Sotho",
    },
    { id => "nso_ZA",
      en_language => "Northern\ Sotho",
      en_territory => "South\ Africa",
      native_language => "Northern\ Sotho",
      native_territory => "South\ Africa",
      real_class => "nso",
    },
    { id => "ny",
      en_language => "Nyanja\;\ Chichewa\;\ Chewa",
      native_language => "Nyanja\;\ Chichewa\;\ Chewa",
    },
    { id => "ny_MW",
      en_language => "Nyanja\;\ Chichewa\;\ Chewa",
      en_territory => "Malawi",
      native_language => "Nyanja\;\ Chichewa\;\ Chewa",
      native_territory => "Malawi",
      real_class => "ny",
    },
    { id => "om",
      en_language => "Oromo",
      native_language => "Oromoo",
    },
    { id => "om_ET",
      en_language => "Oromo",
      en_territory => "Ethiopia",
      native_language => "Oromoo",
      native_territory => "Itoophiyaa",
    },
    { id => "om_KE",
      en_language => "Oromo",
      en_territory => "Kenya",
      native_language => "Oromoo",
      native_territory => "Keeniyaa",
    },
    { id => "pa",
      en_language => "Punjabi",
      native_language => "ਪੰਜਾਬੀ",
    },
    { id => "pa_Arab",
      en_language => "Punjabi",
      en_script => "Arabic",
      native_language => "ਪੰਜਾਬੀ",
      native_script => "Arabic",
    },
    { id => "pa_Arab_PK",
      en_language => "Punjabi",
      en_script => "Arabic",
      en_territory => "Pakistan",
      native_language => "ਪੰਜਾਬੀ",
      native_script => "Arabic",
      native_territory => "Pakistan",
      real_class => "pa_Arab",
    },
    { id => "pa_Guru",
      en_language => "Punjabi",
      en_script => "Gurmukhi",
      native_language => "ਪੰਜਾਬੀ",
      native_script => "گُرمُکھی",
      real_class => "pa",
    },
    { id => "pa_Guru_IN",
      en_language => "Punjabi",
      en_script => "Gurmukhi",
      en_territory => "India",
      native_language => "ਪੰਜਾਬੀ",
      native_script => "گُرمُکھی",
      native_territory => "ਭਾਰਤ",
      real_class => "pa",
    },
    { id => "pa_IN",
      en_language => "Punjabi",
      en_territory => "India",
      native_language => "ਪੰਜਾਬੀ",
      native_territory => "ਭਾਰਤ",
    },
    { id => "pa_PK",
      en_language => "Punjabi",
      en_territory => "Pakistan",
      native_language => "ਪੰਜਾਬੀ",
      native_territory => "Pakistan",
      real_class => "pa",
    },
    { id => "pl",
      en_language => "Polish",
      native_language => "polski",
    },
    { id => "pl_PL",
      en_language => "Polish",
      en_territory => "Poland",
      native_language => "polski",
      native_territory => "Polska",
      real_class => "pl",
    },
    { id => "pt",
      en_language => "Portuguese",
      native_language => "português",
    },
    { id => "pt_BR",
      en_language => "Portuguese",
      en_territory => "Brazil",
      native_language => "português",
      native_territory => "Brasil",
    },
    { id => "pt_PT",
      en_language => "Portuguese",
      en_territory => "Portugal",
      native_language => "português",
      native_territory => "Portugal",
    },
    { id => "ro",
      en_language => "Romanian",
      native_language => "Română",
    },
    { id => "ro_RO",
      en_language => "Romanian",
      en_territory => "Romania",
      native_language => "Română",
      native_territory => "România",
      real_class => "ro",
    },
    { id => "root",
      en_language => "Root",
      native_language => "Root",
    },
    { id => "ru",
      en_language => "Russian",
      native_language => "русский",
    },
    { id => "ru_RU",
      en_language => "Russian",
      en_territory => "Russia",
      native_language => "русский",
      native_territory => "Россия",
      real_class => "ru",
    },
    { id => "ru_UA",
      en_language => "Russian",
      en_territory => "Ukraine",
      native_language => "русский",
      native_territory => "Украина",
    },
    { id => "rw",
      en_language => "Kinyarwanda",
      native_language => "Kinyarwanda",
    },
    { id => "rw_RW",
      en_language => "Kinyarwanda",
      en_territory => "Rwanda",
      native_language => "Kinyarwanda",
      native_territory => "Rwanda",
      real_class => "rw",
    },
    { id => "sh",
      en_language => "Serbo\-Croatian",
      native_language => "Serbo\-Croatian",
      real_class => "sr_Latn",
    },
    { id => "sh_BA",
      en_language => "Serbo\-Croatian",
      en_territory => "Bosnia\ and\ Herzegovina",
      native_language => "Serbo\-Croatian",
      native_territory => "Bosnia\ and\ Herzegovina",
      real_class => "sr_Latn_BA",
    },
    { id => "sh_CS",
      en_language => "Serbo\-Croatian",
      en_territory => "Serbia\ And\ Montenegro",
      native_language => "Serbo\-Croatian",
      native_territory => "Serbia\ And\ Montenegro",
      real_class => "sr_Latn",
    },
    { id => "sh_YU",
      en_language => "Serbo\-Croatian",
      native_language => "Serbo\-Croatian",
      real_class => "sr_Latn",
    },
    { id => "sid",
      en_language => "Sidamo",
      native_language => "Sidaamu\ Afo",
    },
    { id => "sid_ET",
      en_language => "Sidamo",
      en_territory => "Ethiopia",
      native_language => "Sidaamu\ Afo",
      native_territory => "Itiyoophiya",
      real_class => "sid",
    },
    { id => "sk",
      en_language => "Slovak",
      native_language => "slovenský",
    },
    { id => "sk_SK",
      en_language => "Slovak",
      en_territory => "Slovakia",
      native_language => "slovenský",
      native_territory => "Slovenská\ republika",
      real_class => "sk",
    },
    { id => "sl",
      en_language => "Slovenian",
      native_language => "Slovenščina",
    },
    { id => "sl_SI",
      en_language => "Slovenian",
      en_territory => "Slovenia",
      native_language => "Slovenščina",
      native_territory => "Slovenija",
      real_class => "sl",
    },
    { id => "so",
      en_language => "Somali",
      native_language => "Soomaali",
    },
    { id => "so_DJ",
      en_language => "Somali",
      en_territory => "Djibouti",
      native_language => "Soomaali",
      native_territory => "Jabuuti",
      real_class => "so",
    },
    { id => "so_ET",
      en_language => "Somali",
      en_territory => "Ethiopia",
      native_language => "Soomaali",
      native_territory => "Itoobiya",
      real_class => "so",
    },
    { id => "so_KE",
      en_language => "Somali",
      en_territory => "Kenya",
      native_language => "Soomaali",
      native_territory => "Kiiniya",
      real_class => "so",
    },
    { id => "so_SO",
      en_language => "Somali",
      en_territory => "Somalia",
      native_language => "Soomaali",
      native_territory => "Soomaaliya",
      real_class => "so",
    },
    { id => "sq",
      en_language => "Albanian",
      native_language => "shqipe",
    },
    { id => "sq_AL",
      en_language => "Albanian",
      en_territory => "Albania",
      native_language => "shqipe",
      native_territory => "Shqipëria",
      real_class => "sq",
    },
    { id => "sr",
      en_language => "Serbian",
      native_language => "Srpski",
    },
    { id => "sr_BA",
      en_language => "Serbian",
      en_territory => "Bosnia\ and\ Herzegovina",
      native_language => "Srpski",
      native_territory => "Bosna\ i\ Hercegovina",
      real_class => "sr_Cyrl_BA",
    },
    { id => "sr_CS",
      en_language => "Serbian",
      en_territory => "Serbia\ And\ Montenegro",
      native_language => "Srpski",
      native_territory => "Srbija\ i\ Crna\ Gora",
      real_class => "sr_Cyrl",
    },
    { id => "sr_Cyrl",
      en_language => "Serbian",
      en_script => "Cyrillic",
      native_language => "Srpski",
      native_script => "Ćirilica",
    },
    { id => "sr_Cyrl_BA",
      en_language => "Serbian",
      en_script => "Cyrillic",
      en_territory => "Bosnia\ and\ Herzegovina",
      native_language => "Srpski",
      native_script => "Ćirilica",
      native_territory => "Bosna\ i\ Hercegovina",
    },
    { id => "sr_Cyrl_CS",
      en_language => "Serbian",
      en_script => "Cyrillic",
      en_territory => "Serbia\ And\ Montenegro",
      native_language => "Srpski",
      native_script => "Ćirilica",
      native_territory => "Srbija\ i\ Crna\ Gora",
      real_class => "sr_Cyrl",
    },
    { id => "sr_Cyrl_ME",
      en_language => "Serbian",
      en_script => "Cyrillic",
      en_territory => "Montenegro",
      native_language => "Srpski",
      native_script => "Ćirilica",
      native_territory => "Montenegro",
      real_class => "sr_Cyrl",
    },
    { id => "sr_Cyrl_RS",
      en_language => "Serbian",
      en_script => "Cyrillic",
      en_territory => "Serbia",
      native_language => "Srpski",
      native_script => "Ćirilica",
      native_territory => "Serbia",
      real_class => "sr_Cyrl",
    },
    { id => "sr_Cyrl_YU",
      en_language => "Serbian",
      en_script => "Cyrillic",
      native_language => "Srpski",
      native_script => "Ćirilica",
      real_class => "sr_Cyrl",
    },
    { id => "sr_Latn",
      en_language => "Serbian",
      en_script => "Latin",
      native_language => "Srpski",
      native_script => "Latinica",
    },
    { id => "sr_Latn_BA",
      en_language => "Serbian",
      en_script => "Latin",
      en_territory => "Bosnia\ and\ Herzegovina",
      native_language => "Srpski",
      native_script => "Latinica",
      native_territory => "Bosna\ i\ Hercegovina",
    },
    { id => "sr_Latn_CS",
      en_language => "Serbian",
      en_script => "Latin",
      en_territory => "Serbia\ And\ Montenegro",
      native_language => "Srpski",
      native_script => "Latinica",
      native_territory => "Srbija\ i\ Crna\ Gora",
      real_class => "sr_Latn",
    },
    { id => "sr_Latn_ME",
      en_language => "Serbian",
      en_script => "Latin",
      en_territory => "Montenegro",
      native_language => "Srpski",
      native_script => "Latinica",
      native_territory => "Montenegro",
      real_class => "sr_Latn",
    },
    { id => "sr_Latn_RS",
      en_language => "Serbian",
      en_script => "Latin",
      en_territory => "Serbia",
      native_language => "Srpski",
      native_script => "Latinica",
      native_territory => "Serbia",
      real_class => "sr_Latn",
    },
    { id => "sr_Latn_YU",
      en_language => "Serbian",
      en_script => "Latin",
      native_language => "Srpski",
      native_script => "Latinica",
      real_class => "sr_Latn",
    },
    { id => "sr_ME",
      en_language => "Serbian",
      en_territory => "Montenegro",
      native_language => "Srpski",
      native_territory => "Montenegro",
      real_class => "sr_Cyrl",
    },
    { id => "sr_RS",
      en_language => "Serbian",
      en_territory => "Serbia",
      native_language => "Srpski",
      native_territory => "Serbia",
      real_class => "sr_Cyrl",
    },
    { id => "sr_YU",
      en_language => "Serbian",
      native_language => "Srpski",
      real_class => "sr_Cyrl",
    },
    { id => "ss",
      en_language => "Swati",
      native_language => "Swati",
    },
    { id => "ss_ZA",
      en_language => "Swati",
      en_territory => "South\ Africa",
      native_language => "Swati",
      native_territory => "South\ Africa",
      real_class => "ss",
    },
    { id => "st",
      en_language => "Southern\ Sotho",
      native_language => "Southern\ Sotho",
    },
    { id => "st_ZA",
      en_language => "Southern\ Sotho",
      en_territory => "South\ Africa",
      native_language => "Southern\ Sotho",
      native_territory => "South\ Africa",
      real_class => "st",
    },
    { id => "sv",
      en_language => "Swedish",
      native_language => "svenska",
    },
    { id => "sv_FI",
      en_language => "Swedish",
      en_territory => "Finland",
      native_language => "svenska",
      native_territory => "Finland",
      real_class => "sv",
    },
    { id => "sv_SE",
      en_language => "Swedish",
      en_territory => "Sweden",
      native_language => "svenska",
      native_territory => "Sverige",
    },
    { id => "sw",
      en_language => "Swahili",
      native_language => "Kiswahili",
    },
    { id => "sw_KE",
      en_language => "Swahili",
      en_territory => "Kenya",
      native_language => "Kiswahili",
      native_territory => "Kenya",
      real_class => "sw",
    },
    { id => "sw_TZ",
      en_language => "Swahili",
      en_territory => "Tanzania",
      native_language => "Kiswahili",
      native_territory => "Tanzania",
      real_class => "sw",
    },
    { id => "syr",
      en_language => "Syriac",
      native_language => "ܣܘܪܝܝܐ",
    },
    { id => "syr_SY",
      en_language => "Syriac",
      en_territory => "Syria",
      native_language => "ܣܘܪܝܝܐ",
      native_territory => "ܣܘܪܝܝܐ",
    },
    { id => "ta",
      en_language => "Tamil",
      native_language => "தமிழ்",
    },
    { id => "ta_IN",
      en_language => "Tamil",
      en_territory => "India",
      native_language => "தமிழ்",
      native_territory => "இந்தியா",
    },
    { id => "te",
      en_language => "Telugu",
      native_language => "తెలుగు",
    },
    { id => "te_IN",
      en_language => "Telugu",
      en_territory => "India",
      native_language => "తెలుగు",
      native_territory => "భారత\ దేళం",
    },
    { id => "tg",
      en_language => "Tajik",
      native_language => "Tajik",
    },
    { id => "tg_TJ",
      en_language => "Tajik",
      en_territory => "Tajikistan",
      native_language => "Tajik",
      native_territory => "Tajikistan",
      real_class => "tg",
    },
    { id => "th",
      en_language => "Thai",
      native_language => "ไทย",
    },
    { id => "th_TH",
      en_language => "Thai",
      en_territory => "Thailand",
      native_language => "ไทย",
      native_territory => "ประเทศไทย",
      real_class => "th",
    },
    { id => "ti",
      en_language => "Tigrinya",
      native_language => "Tigrinya",
    },
    { id => "ti_ER",
      en_language => "Tigrinya",
      en_territory => "Eritrea",
      native_language => "Tigrinya",
      native_territory => "Eritrea",
    },
    { id => "ti_ET",
      en_language => "Tigrinya",
      en_territory => "Ethiopia",
      native_language => "Tigrinya",
      native_territory => "Ethiopia",
    },
    { id => "tig",
      en_language => "Tigre",
      native_language => "ትግረ",
    },
    { id => "tig_ER",
      en_language => "Tigre",
      en_territory => "Eritrea",
      native_language => "ትግረ",
      native_territory => "ኤርትራ",
    },
    { id => "tn",
      en_language => "Tswana",
      native_language => "Tswana",
    },
    { id => "tn_ZA",
      en_language => "Tswana",
      en_territory => "South\ Africa",
      native_language => "Tswana",
      native_territory => "South\ Africa",
      real_class => "tn",
    },
    { id => "tr",
      en_language => "Turkish",
      native_language => "Türkçe",
    },
    { id => "tr_TR",
      en_language => "Turkish",
      en_territory => "Turkey",
      native_language => "Türkçe",
      native_territory => "Türkiye",
      real_class => "tr",
    },
    { id => "ts",
      en_language => "Tsonga",
      native_language => "Tsonga",
    },
    { id => "ts_ZA",
      en_language => "Tsonga",
      en_territory => "South\ Africa",
      native_language => "Tsonga",
      native_territory => "South\ Africa",
      real_class => "ts",
    },
    { id => "uk",
      en_language => "Ukrainian",
      native_language => "Українська",
    },
    { id => "uk_UA",
      en_language => "Ukrainian",
      en_territory => "Ukraine",
      native_language => "Українська",
      native_territory => "Україна",
      real_class => "uk",
    },
    { id => "uz",
      en_language => "Uzbek",
      native_language => "oʿzbek",
    },
    { id => "uz_AF",
      en_language => "Uzbek",
      en_territory => "Afghanistan",
      native_language => "oʿzbek",
      native_territory => "Afgʿoniston",
      real_class => "uz_Arab",
    },
    { id => "uz_Arab",
      en_language => "Uzbek",
      en_script => "Arabic",
      native_language => "oʿzbek",
      native_script => "Араб",
    },
    { id => "uz_Arab_AF",
      en_language => "Uzbek",
      en_script => "Arabic",
      en_territory => "Afghanistan",
      native_language => "oʿzbek",
      native_script => "Араб",
      native_territory => "Afgʿoniston",
      real_class => "uz_Arab",
    },
    { id => "uz_Cyrl",
      en_language => "Uzbek",
      en_script => "Cyrillic",
      native_language => "oʿzbek",
      native_script => "Kiril",
      real_class => "uz",
    },
    { id => "uz_Cyrl_UZ",
      en_language => "Uzbek",
      en_script => "Cyrillic",
      en_territory => "Uzbekistan",
      native_language => "oʿzbek",
      native_script => "Kiril",
      native_territory => "Oʿzbekiston",
      real_class => "uz",
    },
    { id => "uz_Latn",
      en_language => "Uzbek",
      en_script => "Latin",
      native_language => "oʿzbek",
      native_script => "Lotin",
    },
    { id => "uz_Latn_UZ",
      en_language => "Uzbek",
      en_script => "Latin",
      en_territory => "Uzbekistan",
      native_language => "oʿzbek",
      native_script => "Lotin",
      native_territory => "Oʿzbekiston",
      real_class => "uz_Latn",
    },
    { id => "uz_UZ",
      en_language => "Uzbek",
      en_territory => "Uzbekistan",
      native_language => "oʿzbek",
      native_territory => "Oʿzbekiston",
      real_class => "uz",
    },
    { id => "ve",
      en_language => "Venda",
      native_language => "Venda",
    },
    { id => "ve_ZA",
      en_language => "Venda",
      en_territory => "South\ Africa",
      native_language => "Venda",
      native_territory => "South\ Africa",
      real_class => "ve",
    },
    { id => "vi",
      en_language => "Vietnamese",
      native_language => "Tiếng\ Việt",
    },
    { id => "vi_VN",
      en_language => "Vietnamese",
      en_territory => "Vietnam",
      native_language => "Tiếng\ Việt",
      native_territory => "Việt\ Nam",
      real_class => "vi",
    },
    { id => "wal",
      en_language => "Walamo",
      native_language => "ወላይታቱ",
    },
    { id => "wal_ET",
      en_language => "Walamo",
      en_territory => "Ethiopia",
      native_language => "ወላይታቱ",
      native_territory => "ኢትዮጵያ",
    },
    { id => "xh",
      en_language => "Xhosa",
      native_language => "Xhosa",
    },
    { id => "xh_ZA",
      en_language => "Xhosa",
      en_territory => "South\ Africa",
      native_language => "Xhosa",
      native_territory => "South\ Africa",
      real_class => "xh",
    },
    { id => "yo",
      en_language => "Yoruba",
      native_language => "Yoruba",
    },
    { id => "yo_NG",
      en_language => "Yoruba",
      en_territory => "Nigeria",
      native_language => "Yoruba",
      native_territory => "Nigeria",
      real_class => "yo",
    },
    { id => "zh",
      en_language => "Chinese",
      native_language => "中文",
    },
    { id => "zh_CN",
      en_language => "Chinese",
      en_territory => "China",
      native_language => "中文",
      native_territory => "中華人民共和國",
      real_class => "zh_Hans_CN",
    },
    { id => "zh_HK",
      en_language => "Chinese",
      en_territory => "Hong\ Kong\ SAR\ China",
      native_language => "中文",
      native_territory => "中華人民共和國香港特別行政區",
      real_class => "zh_Hant_HK",
    },
    { id => "zh_Hans",
      en_language => "Chinese",
      en_script => "Simplified\ Han",
      native_language => "中文",
      native_script => "簡體中文",
      real_class => "zh",
    },
    { id => "zh_Hans_CN",
      en_language => "Chinese",
      en_script => "Simplified\ Han",
      en_territory => "China",
      native_language => "中文",
      native_script => "簡體中文",
      native_territory => "中華人民共和國",
    },
    { id => "zh_Hans_SG",
      en_language => "Chinese",
      en_script => "Simplified\ Han",
      en_territory => "Singapore",
      native_language => "中文",
      native_script => "簡體中文",
      native_territory => "新加坡",
    },
    { id => "zh_Hant",
      en_language => "Chinese",
      en_script => "Traditional\ Han",
      native_language => "中文",
      native_script => "繁體漢語",
    },
    { id => "zh_Hant_HK",
      en_language => "Chinese",
      en_script => "Traditional\ Han",
      en_territory => "Hong\ Kong\ SAR\ China",
      native_language => "中文",
      native_script => "繁體漢語",
      native_territory => "中華人民共和國香港特別行政區",
    },
    { id => "zh_Hant_MO",
      en_language => "Chinese",
      en_script => "Traditional\ Han",
      en_territory => "Macao\ SAR\ China",
      native_language => "中文",
      native_script => "繁體漢語",
      native_territory => "澳門特別行政區",
    },
    { id => "zh_Hant_TW",
      en_language => "Chinese",
      en_script => "Traditional\ Han",
      en_territory => "Taiwan",
      native_language => "中文",
      native_script => "繁體漢語",
      native_territory => "臺灣",
      real_class => "zh_Hant",
    },
    { id => "zh_MO",
      en_language => "Chinese",
      en_territory => "Macao\ SAR\ China",
      native_language => "中文",
      native_territory => "澳門特別行政區",
      real_class => "zh_Hant_MO",
    },
    { id => "zh_SG",
      en_language => "Chinese",
      en_territory => "Singapore",
      native_language => "中文",
      native_territory => "新加坡",
      real_class => "zh_Hans_SG",
    },
    { id => "zh_TW",
      en_language => "Chinese",
      en_territory => "Taiwan",
      native_language => "中文",
      native_territory => "臺灣",
      real_class => "zh_Hant",
    },
    { id => "zu",
      en_language => "Zulu",
      native_language => "Zulu",
    },
    { id => "zu_ZA",
      en_language => "Zulu",
      en_territory => "South\ Africa",
      native_language => "Zulu",
      native_territory => "South\ Africa",
      real_class => "zu",
    },
);

%DateTime::Locale::Aliases = (
    C => 'en_US_POSIX',
    POSIX => 'en_US_POSIX',
    afr => 'af',
    afr_ZA => 'af_ZA',
    alb => 'sq',
    alb_AL => 'sq_AL',
    amh => 'am',
    amh_ET => 'am_ET',
    ara => 'ar',
    ara_AE => 'ar_AE',
    ara_BH => 'ar_BH',
    ara_DZ => 'ar_DZ',
    ara_EG => 'ar_EG',
    ara_IQ => 'ar_IQ',
    ara_JO => 'ar_JO',
    ara_KW => 'ar_KW',
    ara_LB => 'ar_LB',
    ara_LY => 'ar_LY',
    ara_MA => 'ar_MA',
    ara_OM => 'ar_OM',
    ara_QA => 'ar_QA',
    ara_SA => 'ar_SA',
    ara_SD => 'ar_SD',
    ara_SY => 'ar_SY',
    ara_TN => 'ar_TN',
    ara_YE => 'ar_YE',
    arm => 'hy',
    arm_AM => 'hy_AM',
    arm_AM_REVISED => 'hy_AM_REVISED',
    aze => 'az',
    aze_AZ => 'az_AZ',
    baq => 'eu',
    baq_ES => 'eu_ES',
    baq_ES_PREEURO => 'eu_ES',
    bel => 'be',
    bel_BY => 'be_BY',
    ben => 'bn',
    ben_IN => 'bn_IN',
    bul => 'bg',
    bul_BG => 'bg_BG',
    cat => 'ca',
    cat_ES => 'ca_ES',
    cat_ES_PREEURO => 'ca_ES',
    ces => 'cs',
    ces_CZ => 'cs_CZ',
    chi => 'zh',
    chi_CN => 'zh_CN',
    chi_HK => 'zh_HK',
    chi_MO => 'zh_MO',
    chi_SG => 'zh_SG',
    chi_TW => 'zh_TW',
    chi_TW_STROKE => 'zh_TW',
    cor => 'kw',
    cor_GB => 'kw_GB',
    cze => 'cs',
    cze_CZ => 'cs_CZ',
    dan => 'da',
    dan_DK => 'da_DK',
    deu => 'de',
    deu_AT => 'de_AT',
    deu_AT_PREEURO => 'de_AT',
    deu_BE => 'de_BE',
    deu_CH => 'de_CH',
    deu_DE => 'de_DE',
    deu_DE_PREEURO => 'de_DE',
    deu_LI => 'de_LI',
    deu_LU => 'de_LU',
    deu_LU_PREEURO => 'de_LU',
    dut => 'nl',
    dut_BE => 'nl_BE',
    dut_BE_PREEURO => 'nl_BE',
    dut_NL => 'nl_NL',
    dut_NL_PREEURO => 'nl_NL',
    ell => 'el',
    ell_GR => 'el_GR',
    ell_GR_PREEURO => 'el_GR',
    eng => 'en',
    eng_AS => 'en_AS',
    eng_AU => 'en_AU',
    eng_BE => 'en_BE',
    eng_BE_PREEURO => 'en_BE',
    eng_BW => 'en_BW',
    eng_BZ => 'en_BZ',
    eng_CA => 'en_CA',
    eng_GB => 'en_GB',
    eng_GB_EURO => 'en_GB',
    eng_GU => 'en_GU',
    eng_HK => 'en_HK',
    eng_IE => 'en_IE',
    eng_IE_PREEURO => 'en_IE',
    eng_IN => 'en_IN',
    eng_JM => 'en_JM',
    eng_MH => 'en_MH',
    eng_MP => 'en_MP',
    eng_MT => 'en_MT',
    eng_NZ => 'en_NZ',
    eng_PH => 'en_PH',
    eng_SG => 'en_SG',
    eng_TT => 'en_TT',
    eng_UM => 'en_UM',
    eng_US => 'en_US',
    eng_US_POSIX => 'en_US_POSIX',
    eng_VI => 'en_VI',
    eng_ZA => 'en_ZA',
    eng_ZW => 'en_ZW',
    epo => 'eo',
    est => 'et',
    est_EE => 'et_EE',
    eus => 'eu',
    eus_ES => 'eu_ES',
    eus_ES_PREEURO => 'eu_ES',
    fao => 'fo',
    fao_FO => 'fo_FO',
    fin => 'fi',
    fin_FI => 'fi_FI',
    fin_FI_PREEURO => 'fi_FI',
    fra => 'fr',
    fra_BE => 'fr_BE',
    fra_BE_PREEURO => 'fr_BE',
    fra_CA => 'fr_CA',
    fra_CH => 'fr_CH',
    fra_FR => 'fr_FR',
    fra_FR_PREEURO => 'fr_FR',
    fra_LU => 'fr_LU',
    fra_LU_PREEURO => 'fr_LU',
    fra_MC => 'fr_MC',
    fre => 'fr',
    fre_BE => 'fr_BE',
    fre_BE_PREEURO => 'fr_BE',
    fre_CA => 'fr_CA',
    fre_CH => 'fr_CH',
    fre_FR => 'fr_FR',
    fre_FR_PREEURO => 'fr_FR',
    fre_LU => 'fr_LU',
    fre_LU_PREEURO => 'fr_LU',
    fre_MC => 'fr_MC',
    geo => 'ka',
    geo_GE => 'ka_GE',
    ger => 'de',
    ger_AT => 'de_AT',
    ger_AT_PREEURO => 'de_AT',
    ger_BE => 'de_BE',
    ger_CH => 'de_CH',
    ger_DE => 'de_DE',
    ger_DE_PREEURO => 'de_DE',
    ger_LI => 'de_LI',
    ger_LU => 'de_LU',
    ger_LU_PREEURO => 'de_LU',
    gle => 'ga',
    gle_IE => 'ga_IE',
    gle_IE_PREEURO => 'ga_IE',
    glg => 'gl',
    glg_ES => 'gl_ES',
    glg_ES_PREEURO => 'gl_ES',
    glv => 'gv',
    glv_GB => 'gv_GB',
    gre => 'el',
    gre_GR => 'el_GR',
    gre_GR_PREEURO => 'el_GR',
    guj => 'gu',
    guj_IN => 'gu_IN',
    heb => 'he',
    heb_IL => 'he_IL',
    hin => 'hi',
    hin_IN => 'hi_IN',
    hrv => 'hr',
    hrv_HR => 'hr_HR',
    hun => 'hu',
    hun_HU => 'hu_HU',
    hye => 'hy',
    hye_AM => 'hy_AM',
    hye_AM_REVISED => 'hy_AM_REVISED',
    ice => 'is',
    ice_IS => 'is_IS',
    ind => 'id',
    ind_ID => 'id_ID',
    isl => 'is',
    isl_IS => 'is_IS',
    ita => 'it',
    ita_CH => 'it_CH',
    ita_IT => 'it_IT',
    ita_IT_PREEURO => 'it_IT',
    iw => 'he',
    iw_IL => 'he_IL',
    jpn => 'ja',
    jpn_JP => 'ja_JP',
    kal => 'kl',
    kal_GL => 'kl_GL',
    kan => 'kn',
    kan_IN => 'kn_IN',
    kat => 'ka',
    kat_GE => 'ka_GE',
    kaz => 'kk',
    kaz_KZ => 'kk_KZ',
    kor => 'ko',
    kor_KR => 'ko_KR',
    lav => 'lv',
    lav_LV => 'lv_LV',
    lit => 'lt',
    lit_LT => 'lt_LT',
    mac => 'mk',
    mac_MK => 'mk_MK',
    mar => 'mr',
    mar_IN => 'mr_IN',
    may => 'ms',
    may_BN => 'ms_BN',
    may_MY => 'ms_MY',
    mkd => 'mk',
    mkd_MK => 'mk_MK',
    mlt => 'mt',
    mlt_MT => 'mt_MT',
    mon => 'mn',
    mon_MN => 'mn_MN',
    msa => 'ms',
    msa_BN => 'ms_BN',
    msa_MY => 'ms_MY',
    nld => 'nl',
    nld_BE => 'nl_BE',
    nld_BE_PREEURO => 'nl_BE',
    nld_NL => 'nl_NL',
    nld_NL_PREEURO => 'nl_NL',
    nno => 'nn',
    nno_NO => 'nn_NO',
    no => 'nn',
    no_NO => 'nn_NO',
    no_NO_NY => 'nn_NO',
    nob => 'nb',
    nob_NO => 'nb_NO',
    orm => 'om',
    orm_ET => 'om_ET',
    orm_KE => 'om_KE',
    pan => 'pa',
    pan_IN => 'pa_IN',
    pol => 'pl',
    pol_PL => 'pl_PL',
    por => 'pt',
    por_BR => 'pt_BR',
    por_PT => 'pt_PT',
    por_PT_PREEURO => 'pt_PT',
    ron => 'ro',
    ron_RO => 'ro_RO',
    rum => 'ro',
    rum_RO => 'ro_RO',
    rus => 'ru',
    rus_RU => 'ru_RU',
    rus_UA => 'ru_UA',
    scc => 'sr',
    scc_YU => 'sr_YU',
    scr => 'hr',
    scr_HR => 'hr_HR',
    slk => 'sk',
    slk_SK => 'sk_SK',
    slo => 'sk',
    slo_SK => 'sk_SK',
    slv => 'sl',
    slv_SI => 'sl_SI',
    som => 'so',
    som_DJ => 'so_DJ',
    som_ET => 'so_ET',
    som_KE => 'so_KE',
    som_SO => 'so_SO',
    spa => 'es',
    spa_AR => 'es_AR',
    spa_BO => 'es_BO',
    spa_CL => 'es_CL',
    spa_CO => 'es_CO',
    spa_CR => 'es_CR',
    spa_DO => 'es_DO',
    spa_EC => 'es_EC',
    spa_ES => 'es_ES',
    spa_ES_PREEURO => 'es_ES',
    spa_GT => 'es_GT',
    spa_HN => 'es_HN',
    spa_MX => 'es_MX',
    spa_NI => 'es_NI',
    spa_PA => 'es_PA',
    spa_PE => 'es_PE',
    spa_PR => 'es_PR',
    spa_PY => 'es_PY',
    spa_SV => 'es_SV',
    spa_US => 'es_US',
    spa_UY => 'es_UY',
    spa_VE => 'es_VE',
    sqi => 'sq',
    sqi_AL => 'sq_AL',
    srp => 'sr',
    srp_YU => 'sr_YU',
    swa => 'sw',
    swa_KE => 'sw_KE',
    swa_TZ => 'sw_TZ',
    swe => 'sv',
    swe_FI => 'sv_FI',
    swe_SE => 'sv_SE',
    tam => 'ta',
    tam_IN => 'ta_IN',
    tel => 'te',
    tel_IN => 'te_IN',
    tha => 'th',
    tha_TH => 'th_TH',
    tur => 'tr',
    tur_TR => 'tr_TR',
    ukr => 'uk',
    ukr_UA => 'uk_UA',
    uzb => 'uz',
    uzb_UZ => 'uz_UZ',
    vie => 'vi',
    vie_VN => 'vi_VN',
    zho => 'zh',
    zho_CN => 'zh_CN',
    zho_HK => 'zh_HK',
    zho_MO => 'zh_MO',
    zho_SG => 'zh_SG',
    zho_TW => 'zh_TW',
    zho_TW_STROKE => 'zh_TW',
);

1;

__END__

=head1 NAME

DateTime::LocaleCatalog - Provides a list of all valid locale names

=head1 SYNOPSIS

See DateTime::Locale for usage details.

=head1 DESCRIPTION

This module contains a list of all known locales.

=head1 LOCALES

Any method taking locale id or name arguments should use one of the
values listed below.  Ids and names are case sensitive.

Always select the closest matching locale - for example, French
Canadians would choose fr_CA over fr - and B<always> use locale ids in
preference to names; locale ids offer greater compatibility when using
localized third party modules.

Many of the available locales are the same as other, more generic
locales for datetime information.  In that case, we simply load the
more generic class.  However, the various methods related to name,
territory, and variant return the values for the requested locale.

The available locales are:

 Locale id           Locale name
 ==================================================
 aa                  Afar
 aa_DJ               Afar Djibouti
 aa_ER               Afar Eritrea
 aa_ER_SAAHO         Afar Eritrea Saaho
 aa_ET               Afar Ethiopia
 af                  Afrikaans
 af_NA               Afrikaans Namibia
 af_ZA               Afrikaans South Africa
 ak                  Akan
 ak_GH               Akan Ghana
 am                  Amharic
 am_ET               Amharic Ethiopia
 ar                  Arabic
 ar_AE               Arabic United Arab Emirates
 ar_BH               Arabic Bahrain
 ar_DZ               Arabic Algeria
 ar_EG               Arabic Egypt
 ar_IQ               Arabic Iraq
 ar_JO               Arabic Jordan
 ar_KW               Arabic Kuwait
 ar_LB               Arabic Lebanon
 ar_LY               Arabic Libya
 ar_MA               Arabic Morocco
 ar_OM               Arabic Oman
 ar_QA               Arabic Qatar
 ar_SA               Arabic Saudi Arabia
 ar_SD               Arabic Sudan
 ar_SY               Arabic Syria
 ar_TN               Arabic Tunisia
 ar_YE               Arabic Yemen
 as                  Assamese
 as_IN               Assamese India
 az                  Azerbaijani
 az_AZ               Azerbaijani Azerbaijan
 az_Cyrl             Azerbaijani (Cyrillic)
 az_Cyrl_AZ          Azerbaijani Azerbaijan (Cyrillic)
 az_Latn             Azerbaijani (Latin)
 az_Latn_AZ          Azerbaijani Azerbaijan (Latin)
 be                  Belarusian
 be_BY               Belarusian Belarus
 bg                  Bulgarian
 bg_BG               Bulgarian Bulgaria
 bn                  Bengali
 bn_BD               Bengali Bangladesh
 bn_IN               Bengali India
 bs                  Bosnian
 bs_BA               Bosnian Bosnia and Herzegovina
 byn                 Blin
 byn_ER              Blin Eritrea
 ca                  Catalan
 ca_ES               Catalan Spain
 cch                 Atsam
 cch_NG              Atsam Nigeria
 cs                  Czech
 cs_CZ               Czech Czech Republic
 cy                  Welsh
 cy_GB               Welsh United Kingdom
 da                  Danish
 da_DK               Danish Denmark
 de                  German
 de_AT               German Austria
 de_BE               German Belgium
 de_CH               German Switzerland
 de_DE               German Germany
 de_LI               German Liechtenstein
 de_LU               German Luxembourg
 dz                  Dzongkha
 dz_BT               Dzongkha Bhutan
 ee                  Ewe
 ee_GH               Ewe Ghana
 ee_TG               Ewe Togo
 el                  Greek
 el_CY               Greek Cyprus
 el_GR               Greek Greece
 el_POLYTONI         Greek
 en                  English
 en_AS               English American Samoa
 en_AU               English Australia
 en_BE               English Belgium
 en_BW               English Botswana
 en_BZ               English Belize
 en_CA               English Canada
 en_GB               English United Kingdom
 en_GU               English Guam
 en_HK               English Hong Kong SAR China
 en_IE               English Ireland
 en_IN               English India
 en_JM               English Jamaica
 en_MH               English Marshall Islands
 en_MP               English Northern Mariana Islands
 en_MT               English Malta
 en_NA               English Namibia
 en_NZ               English New Zealand
 en_PH               English Philippines
 en_PK               English Pakistan
 en_SG               English Singapore
 en_TT               English Trinidad and Tobago
 en_UM               English United States Minor Outlying Islands
 en_US               English United States
 en_US_POSIX         English United States Posix
 en_VI               English U.S. Virgin Islands
 en_ZA               English South Africa
 en_ZW               English Zimbabwe
 eo                  Esperanto
 es                  Spanish
 es_AR               Spanish Argentina
 es_BO               Spanish Bolivia
 es_CL               Spanish Chile
 es_CO               Spanish Colombia
 es_CR               Spanish Costa Rica
 es_DO               Spanish Dominican Republic
 es_EC               Spanish Ecuador
 es_ES               Spanish Spain
 es_GT               Spanish Guatemala
 es_HN               Spanish Honduras
 es_MX               Spanish Mexico
 es_NI               Spanish Nicaragua
 es_PA               Spanish Panama
 es_PE               Spanish Peru
 es_PR               Spanish Puerto Rico
 es_PY               Spanish Paraguay
 es_SV               Spanish El Salvador
 es_US               Spanish United States
 es_UY               Spanish Uruguay
 es_VE               Spanish Venezuela
 et                  Estonian
 et_EE               Estonian Estonia
 eu                  Basque
 eu_ES               Basque Spain
 fi                  Finnish
 fi_FI               Finnish Finland
 fo                  Faroese
 fo_FO               Faroese Faroe Islands
 fr                  French
 fr_BE               French Belgium
 fr_CA               French Canada
 fr_CH               French Switzerland
 fr_FR               French France
 fr_LU               French Luxembourg
 fr_MC               French Monaco
 fur                 Friulian
 fur_IT              Friulian Italy
 ga                  Irish
 ga_IE               Irish Ireland
 gaa                 Ga
 gaa_GH              Ga Ghana
 gez                 Geez
 gez_ER              Geez Eritrea
 gez_ET              Geez Ethiopia
 gl                  Galician
 gl_ES               Galician Spain
 gu                  Gujarati
 gu_IN               Gujarati India
 gv                  Manx
 gv_GB               Manx United Kingdom
 ha                  Hausa
 ha_Arab             Hausa (Arabic)
 ha_Arab_NG          Hausa Nigeria (Arabic)
 ha_GH               Hausa Ghana
 ha_Latn             Hausa (Latin)
 ha_Latn_GH          Hausa Ghana (Latin)
 ha_Latn_NE          Hausa Niger (Latin)
 ha_Latn_NG          Hausa Nigeria (Latin)
 ha_NE               Hausa Niger
 ha_NG               Hausa Nigeria
 haw                 Hawaiian
 haw_US              Hawaiian United States
 he                  Hebrew
 he_IL               Hebrew Israel
 hi                  Hindi
 hi_IN               Hindi India
 hr                  Croatian
 hr_HR               Croatian Croatia
 hu                  Hungarian
 hu_HU               Hungarian Hungary
 hy                  Armenian
 hy_AM               Armenian Armenia
 hy_AM_REVISED       Armenian Armenia Revised
 ia                  Interlingua
 id                  Indonesian
 id_ID               Indonesian Indonesia
 ig                  Igbo
 ig_NG               Igbo Nigeria
 is                  Icelandic
 is_IS               Icelandic Iceland
 it                  Italian
 it_CH               Italian Switzerland
 it_IT               Italian Italy
 iu                  Inuktitut
 ja                  Japanese
 ja_JP               Japanese Japan
 ka                  Georgian
 ka_GE               Georgian Georgia
 kaj                 Jju
 kaj_NG              Jju Nigeria
 kam                 Kamba
 kam_KE              Kamba Kenya
 kcg                 Tyap
 kcg_NG              Tyap Nigeria
 kfo                 Koro
 kfo_NG              Koro Nigeria
 kk                  Kazakh
 kk_KZ               Kazakh Kazakhstan
 kl                  Kalaallisut
 kl_GL               Kalaallisut Greenland
 km                  Khmer
 km_KH               Khmer Cambodia
 kn                  Kannada
 kn_IN               Kannada India
 ko                  Korean
 ko_KR               Korean South Korea
 kok                 Konkani
 kok_IN              Konkani India
 kw                  Cornish
 kw_GB               Cornish United Kingdom
 ln                  Lingala
 ln_CD               Lingala Congo (Kinshasa)
 ln_CG               Lingala Congo (Brazzaville)
 lo                  Lao
 lo_LA               Lao Laos
 lt                  Lithuanian
 lt_LT               Lithuanian Lithuania
 lv                  Latvian
 lv_LV               Latvian Latvia
 mk                  Macedonian
 mk_MK               Macedonian Macedonia
 ml                  Malayalam
 ml_IN               Malayalam India
 mn                  Mongolian
 mn_MN               Mongolian Mongolia
 mr                  Marathi
 mr_IN               Marathi India
 ms                  Malay
 ms_BN               Malay Brunei
 ms_MY               Malay Malaysia
 mt                  Maltese
 mt_MT               Maltese Malta
 nb                  Norwegian Bokmål
 nb_NO               Norwegian Bokmål Norway
 ne                  Nepali
 ne_NP               Nepali Nepal
 nl                  Dutch
 nl_BE               Dutch Belgium
 nl_NL               Dutch Netherlands
 nn                  Norwegian Nynorsk
 nn_NO               Norwegian Nynorsk Norway
 nr                  South Ndebele
 nr_ZA               South Ndebele South Africa
 nso                 Northern Sotho
 nso_ZA              Northern Sotho South Africa
 ny                  Nyanja; Chichewa; Chewa
 ny_MW               Nyanja; Chichewa; Chewa Malawi
 om                  Oromo
 om_ET               Oromo Ethiopia
 om_KE               Oromo Kenya
 pa                  Punjabi
 pa_Arab             Punjabi (Arabic)
 pa_Arab_PK          Punjabi Pakistan (Arabic)
 pa_Guru             Punjabi (Gurmukhi)
 pa_Guru_IN          Punjabi India (Gurmukhi)
 pa_IN               Punjabi India
 pa_PK               Punjabi Pakistan
 pl                  Polish
 pl_PL               Polish Poland
 pt                  Portuguese
 pt_BR               Portuguese Brazil
 pt_PT               Portuguese Portugal
 ro                  Romanian
 ro_RO               Romanian Romania
 root                Root
 ru                  Russian
 ru_RU               Russian Russia
 ru_UA               Russian Ukraine
 rw                  Kinyarwanda
 rw_RW               Kinyarwanda Rwanda
 sh                  Serbo-Croatian
 sh_BA               Serbo-Croatian Bosnia and Herzegovina
 sh_CS               Serbo-Croatian Serbia And Montenegro
 sh_YU               Serbo-Croatian
 sid                 Sidamo
 sid_ET              Sidamo Ethiopia
 sk                  Slovak
 sk_SK               Slovak Slovakia
 sl                  Slovenian
 sl_SI               Slovenian Slovenia
 so                  Somali
 so_DJ               Somali Djibouti
 so_ET               Somali Ethiopia
 so_KE               Somali Kenya
 so_SO               Somali Somalia
 sq                  Albanian
 sq_AL               Albanian Albania
 sr                  Serbian
 sr_BA               Serbian Bosnia and Herzegovina
 sr_CS               Serbian Serbia And Montenegro
 sr_Cyrl             Serbian (Cyrillic)
 sr_Cyrl_BA          Serbian Bosnia and Herzegovina (Cyrillic)
 sr_Cyrl_CS          Serbian Serbia And Montenegro (Cyrillic)
 sr_Cyrl_ME          Serbian Montenegro (Cyrillic)
 sr_Cyrl_RS          Serbian Serbia (Cyrillic)
 sr_Cyrl_YU          Serbian (Cyrillic)
 sr_Latn             Serbian (Latin)
 sr_Latn_BA          Serbian Bosnia and Herzegovina (Latin)
 sr_Latn_CS          Serbian Serbia And Montenegro (Latin)
 sr_Latn_ME          Serbian Montenegro (Latin)
 sr_Latn_RS          Serbian Serbia (Latin)
 sr_Latn_YU          Serbian (Latin)
 sr_ME               Serbian Montenegro
 sr_RS               Serbian Serbia
 sr_YU               Serbian
 ss                  Swati
 ss_ZA               Swati South Africa
 st                  Southern Sotho
 st_ZA               Southern Sotho South Africa
 sv                  Swedish
 sv_FI               Swedish Finland
 sv_SE               Swedish Sweden
 sw                  Swahili
 sw_KE               Swahili Kenya
 sw_TZ               Swahili Tanzania
 syr                 Syriac
 syr_SY              Syriac Syria
 ta                  Tamil
 ta_IN               Tamil India
 te                  Telugu
 te_IN               Telugu India
 tg                  Tajik
 tg_TJ               Tajik Tajikistan
 th                  Thai
 th_TH               Thai Thailand
 ti                  Tigrinya
 ti_ER               Tigrinya Eritrea
 ti_ET               Tigrinya Ethiopia
 tig                 Tigre
 tig_ER              Tigre Eritrea
 tn                  Tswana
 tn_ZA               Tswana South Africa
 tr                  Turkish
 tr_TR               Turkish Turkey
 ts                  Tsonga
 ts_ZA               Tsonga South Africa
 uk                  Ukrainian
 uk_UA               Ukrainian Ukraine
 uz                  Uzbek
 uz_AF               Uzbek Afghanistan
 uz_Arab             Uzbek (Arabic)
 uz_Arab_AF          Uzbek Afghanistan (Arabic)
 uz_Cyrl             Uzbek (Cyrillic)
 uz_Cyrl_UZ          Uzbek Uzbekistan (Cyrillic)
 uz_Latn             Uzbek (Latin)
 uz_Latn_UZ          Uzbek Uzbekistan (Latin)
 uz_UZ               Uzbek Uzbekistan
 ve                  Venda
 ve_ZA               Venda South Africa
 vi                  Vietnamese
 vi_VN               Vietnamese Vietnam
 wal                 Walamo
 wal_ET              Walamo Ethiopia
 xh                  Xhosa
 xh_ZA               Xhosa South Africa
 yo                  Yoruba
 yo_NG               Yoruba Nigeria
 zh                  Chinese
 zh_CN               Chinese China
 zh_HK               Chinese Hong Kong SAR China
 zh_Hans             Chinese (Simplified Han)
 zh_Hans_CN          Chinese China (Simplified Han)
 zh_Hans_SG          Chinese Singapore (Simplified Han)
 zh_Hant             Chinese (Traditional Han)
 zh_Hant_HK          Chinese Hong Kong SAR China (Traditional Han)
 zh_Hant_MO          Chinese Macao SAR China (Traditional Han)
 zh_Hant_TW          Chinese Taiwan (Traditional Han)
 zh_MO               Chinese Macao SAR China
 zh_SG               Chinese Singapore
 zh_TW               Chinese Taiwan
 zu                  Zulu
 zu_ZA               Zulu South Africa


There are also many aliases available, mostly for three-letter
language codes, these are:

 Locale id           Is an alias for
 ==================================================
 C                   en_US_POSIX
 POSIX               en_US_POSIX
 afr                 af
 afr_ZA              af_ZA
 alb                 sq
 alb_AL              sq_AL
 amh                 am
 amh_ET              am_ET
 ara                 ar
 ara_AE              ar_AE
 ara_BH              ar_BH
 ara_DZ              ar_DZ
 ara_EG              ar_EG
 ara_IQ              ar_IQ
 ara_JO              ar_JO
 ara_KW              ar_KW
 ara_LB              ar_LB
 ara_LY              ar_LY
 ara_MA              ar_MA
 ara_OM              ar_OM
 ara_QA              ar_QA
 ara_SA              ar_SA
 ara_SD              ar_SD
 ara_SY              ar_SY
 ara_TN              ar_TN
 ara_YE              ar_YE
 arm                 hy
 arm_AM              hy_AM
 arm_AM_REVISED      hy_AM_REVISED
 aze                 az
 aze_AZ              az_AZ
 baq                 eu
 baq_ES              eu_ES
 baq_ES_PREEURO      eu_ES
 bel                 be
 bel_BY              be_BY
 ben                 bn
 ben_IN              bn_IN
 bul                 bg
 bul_BG              bg_BG
 cat                 ca
 cat_ES              ca_ES
 cat_ES_PREEURO      ca_ES
 ces                 cs
 ces_CZ              cs_CZ
 chi                 zh
 chi_CN              zh_CN
 chi_HK              zh_HK
 chi_MO              zh_MO
 chi_SG              zh_SG
 chi_TW              zh_TW
 chi_TW_STROKE       zh_TW
 cor                 kw
 cor_GB              kw_GB
 cze                 cs
 cze_CZ              cs_CZ
 dan                 da
 dan_DK              da_DK
 deu                 de
 deu_AT              de_AT
 deu_AT_PREEURO      de_AT
 deu_BE              de_BE
 deu_CH              de_CH
 deu_DE              de_DE
 deu_DE_PREEURO      de_DE
 deu_LI              de_LI
 deu_LU              de_LU
 deu_LU_PREEURO      de_LU
 dut                 nl
 dut_BE              nl_BE
 dut_BE_PREEURO      nl_BE
 dut_NL              nl_NL
 dut_NL_PREEURO      nl_NL
 ell                 el
 ell_GR              el_GR
 ell_GR_PREEURO      el_GR
 eng                 en
 eng_AS              en_AS
 eng_AU              en_AU
 eng_BE              en_BE
 eng_BE_PREEURO      en_BE
 eng_BW              en_BW
 eng_BZ              en_BZ
 eng_CA              en_CA
 eng_GB              en_GB
 eng_GB_EURO         en_GB
 eng_GU              en_GU
 eng_HK              en_HK
 eng_IE              en_IE
 eng_IE_PREEURO      en_IE
 eng_IN              en_IN
 eng_JM              en_JM
 eng_MH              en_MH
 eng_MP              en_MP
 eng_MT              en_MT
 eng_NZ              en_NZ
 eng_PH              en_PH
 eng_SG              en_SG
 eng_TT              en_TT
 eng_UM              en_UM
 eng_US              en_US
 eng_US_POSIX        en_US_POSIX
 eng_VI              en_VI
 eng_ZA              en_ZA
 eng_ZW              en_ZW
 epo                 eo
 est                 et
 est_EE              et_EE
 eus                 eu
 eus_ES              eu_ES
 eus_ES_PREEURO      eu_ES
 fao                 fo
 fao_FO              fo_FO
 fin                 fi
 fin_FI              fi_FI
 fin_FI_PREEURO      fi_FI
 fra                 fr
 fra_BE              fr_BE
 fra_BE_PREEURO      fr_BE
 fra_CA              fr_CA
 fra_CH              fr_CH
 fra_FR              fr_FR
 fra_FR_PREEURO      fr_FR
 fra_LU              fr_LU
 fra_LU_PREEURO      fr_LU
 fra_MC              fr_MC
 fre                 fr
 fre_BE              fr_BE
 fre_BE_PREEURO      fr_BE
 fre_CA              fr_CA
 fre_CH              fr_CH
 fre_FR              fr_FR
 fre_FR_PREEURO      fr_FR
 fre_LU              fr_LU
 fre_LU_PREEURO      fr_LU
 fre_MC              fr_MC
 geo                 ka
 geo_GE              ka_GE
 ger                 de
 ger_AT              de_AT
 ger_AT_PREEURO      de_AT
 ger_BE              de_BE
 ger_CH              de_CH
 ger_DE              de_DE
 ger_DE_PREEURO      de_DE
 ger_LI              de_LI
 ger_LU              de_LU
 ger_LU_PREEURO      de_LU
 gle                 ga
 gle_IE              ga_IE
 gle_IE_PREEURO      ga_IE
 glg                 gl
 glg_ES              gl_ES
 glg_ES_PREEURO      gl_ES
 glv                 gv
 glv_GB              gv_GB
 gre                 el
 gre_GR              el_GR
 gre_GR_PREEURO      el_GR
 guj                 gu
 guj_IN              gu_IN
 heb                 he
 heb_IL              he_IL
 hin                 hi
 hin_IN              hi_IN
 hrv                 hr
 hrv_HR              hr_HR
 hun                 hu
 hun_HU              hu_HU
 hye                 hy
 hye_AM              hy_AM
 hye_AM_REVISED      hy_AM_REVISED
 ice                 is
 ice_IS              is_IS
 ind                 id
 ind_ID              id_ID
 isl                 is
 isl_IS              is_IS
 ita                 it
 ita_CH              it_CH
 ita_IT              it_IT
 ita_IT_PREEURO      it_IT
 iw                  he
 iw_IL               he_IL
 jpn                 ja
 jpn_JP              ja_JP
 kal                 kl
 kal_GL              kl_GL
 kan                 kn
 kan_IN              kn_IN
 kat                 ka
 kat_GE              ka_GE
 kaz                 kk
 kaz_KZ              kk_KZ
 kor                 ko
 kor_KR              ko_KR
 lav                 lv
 lav_LV              lv_LV
 lit                 lt
 lit_LT              lt_LT
 mac                 mk
 mac_MK              mk_MK
 mar                 mr
 mar_IN              mr_IN
 may                 ms
 may_BN              ms_BN
 may_MY              ms_MY
 mkd                 mk
 mkd_MK              mk_MK
 mlt                 mt
 mlt_MT              mt_MT
 mon                 mn
 mon_MN              mn_MN
 msa                 ms
 msa_BN              ms_BN
 msa_MY              ms_MY
 nld                 nl
 nld_BE              nl_BE
 nld_BE_PREEURO      nl_BE
 nld_NL              nl_NL
 nld_NL_PREEURO      nl_NL
 nno                 nn
 nno_NO              nn_NO
 no                  nn
 no_NO               nn_NO
 no_NO_NY            nn_NO
 nob                 nb
 nob_NO              nb_NO
 orm                 om
 orm_ET              om_ET
 orm_KE              om_KE
 pan                 pa
 pan_IN              pa_IN
 pol                 pl
 pol_PL              pl_PL
 por                 pt
 por_BR              pt_BR
 por_PT              pt_PT
 por_PT_PREEURO      pt_PT
 ron                 ro
 ron_RO              ro_RO
 rum                 ro
 rum_RO              ro_RO
 rus                 ru
 rus_RU              ru_RU
 rus_UA              ru_UA
 scc                 sr
 scc_YU              sr_YU
 scr                 hr
 scr_HR              hr_HR
 slk                 sk
 slk_SK              sk_SK
 slo                 sk
 slo_SK              sk_SK
 slv                 sl
 slv_SI              sl_SI
 som                 so
 som_DJ              so_DJ
 som_ET              so_ET
 som_KE              so_KE
 som_SO              so_SO
 spa                 es
 spa_AR              es_AR
 spa_BO              es_BO
 spa_CL              es_CL
 spa_CO              es_CO
 spa_CR              es_CR
 spa_DO              es_DO
 spa_EC              es_EC
 spa_ES              es_ES
 spa_ES_PREEURO      es_ES
 spa_GT              es_GT
 spa_HN              es_HN
 spa_MX              es_MX
 spa_NI              es_NI
 spa_PA              es_PA
 spa_PE              es_PE
 spa_PR              es_PR
 spa_PY              es_PY
 spa_SV              es_SV
 spa_US              es_US
 spa_UY              es_UY
 spa_VE              es_VE
 sqi                 sq
 sqi_AL              sq_AL
 srp                 sr
 srp_YU              sr_YU
 swa                 sw
 swa_KE              sw_KE
 swa_TZ              sw_TZ
 swe                 sv
 swe_FI              sv_FI
 swe_SE              sv_SE
 tam                 ta
 tam_IN              ta_IN
 tel                 te
 tel_IN              te_IN
 tha                 th
 tha_TH              th_TH
 tur                 tr
 tur_TR              tr_TR
 ukr                 uk
 ukr_UA              uk_UA
 uzb                 uz
 uzb_UZ              uz_UZ
 vie                 vi
 vie_VN              vi_VN
 zho                 zh
 zho_CN              zh_CN
 zho_HK              zh_HK
 zho_MO              zh_MO
 zho_SG              zh_SG
 zho_TW              zh_TW
 zho_TW_STROKE       zh_TW


=cut
