
=begin comment

!!Note that if you change the format or layout of this page you must also 
modify the code/common/mh_release.pl file to search the new format!!

=end comment

=head1 Download Misterhouse

=head1 Current Stable

B<Version 3.1> - released on 03/31/2014

=over

=item Linux, Windows and MacOS

L<https://api.github.com/repos/hollie/misterhouse/zipball/v3.1>

The Windows only compiled version of Misterhouse is sadly no longer supported.

Between formal releases, you can pick up the latest updates from: L<https://github.com/hollie/misterhouse> (not recommended for beginners!)

A large (30MB) zip of optional files (mainly sound files) is here: L<http://misterhouse.sf.net/misterhouse_misc.zip>

=back

=head1 Previous Stable

B<Version 3.0> - released on 06/20/2013

=over

=item * 

=begin HTML

<strong>
<a href='https://api.github.com/repos/hollie/misterhouse/zipball/v3.0' target='_blank'>https://api.github.com/repos/hollie/misterhouse/zipball/v3.0</a>
</strong>

=end HTML

=back

=head1 Older Versions

=over

=item * You can get older versions from Sourceforge (not recommended): 

=begin HTML

<strong>
<a href='http://sourceforge.net/project/showfiles.php?group_id=1365&package_id=1347' target='_blank'>
http://sourceforge.net/project/showfiles.php?group_id=1365&package_id=1347
</a>
</strong>

=end HTML

=back

=head1 Mailing List

Subscribe to the Misterhouse release announcement mailing list here:  L<http://lists.sourceforge.net/mailman/listinfo/misterhouse-announce>

Or join the Misterhouse community mailing list here: L<http://lists.sourceforge.net/mailman/listinfo/misterhouse-users>

Last modified 03/02/2013 11:03:55

=cut
