
=begin comment

!!Note that if you change the format or layout of this page you must also 
modify the code/common/mh_release.pl file to search the new format!!

=end comment

=head1 Download Misterhouse

=head1 Current Stable

B<Version 6.0> - released on 11/11/2024

=over

=item Linux, Windows and MacOS

L<https://api.github.com/repos/hollie/misterhouse/zipball/v6.0>

The Windows only compiled version of Misterhouse is sadly no longer supported.

Between formal releases, you can pick up the latest updates from: L<https://github.com/hollie/misterhouse>

A large (30MB) zip of optional files (mainly sound files) is here: L<http://misterhouse.sf.net/misterhouse_misc.zip>

=back

=head1 Previous Stable

B<Version 5.0> - released on 10/31/2017

=over

=item Linux, Windows and MacOS

L<https://api.github.com/repos/hollie/misterhouse/zipball/v5.0>

The Windows only compiled version of Misterhouse is sadly no longer supported.

=back

=head1Older Versions

B<Version 4.2> - released on 03/08/2017

=over

=item * 

=begin HTML

<strong>
<a href='https://api.github.com/repos/hollie/misterhouse/zipball/v3.0' target='_blank'>https://api.github.com/repos/hollie/misterhouse/zipball/v4.2</a>
</strong>

=end HTML

=back

=end HTML

=back

=head1 Mailing List

Subscribe to the Misterhouse release announcement mailing list here:  L<http://lists.sourceforge.net/mailman/listinfo/misterhouse-announce>

Or join the Misterhouse community mailing list here: L<http://lists.sourceforge.net/mailman/listinfo/misterhouse-users>

Last modified 10/31/2017 

=cut
